import type { DmrvFamilyId } from './dmrvCatalog';
import { segmentColorForIndex } from './dmrvInfographicTheme';

export type InfographicTypeSeed = {
  id: string;
  selectorLabel: string;
  label: string;
  description: string;
  inputExamples: string[];
  evaluationFocus: string[];
};

function row(
  id: string,
  selectorLabel: string,
  label: string,
  description: string,
  inputExamples: string[],
  evaluationFocus: string[],
): InfographicTypeSeed {
  return { id, selectorLabel, label, description, inputExamples, evaluationFocus };
}

/** Eight DMRV types per family — aligned with DPAL Adaptive DMRV infographic boards. */
export const DMRV_INFOGRAPHIC_TYPES: Record<DmrvFamilyId, InfographicTypeSeed[]> = {
  'carbon-land': [
    row(
      'forest-land-use',
      'Forest / Land Use',
      'Forest / Land Use DMRV',
      'Monitors forest carbon stocks, deforestation, degradation, regrowth, and land-cover change.',
      ['Satellite Imagery', 'LiDAR', 'Field Plots', 'Biomass Data', 'Activity Data'],
      ['Land cover change', 'Biomass / carbon stock', 'Deforestation alerts', 'Regrowth trends'],
    ),
    row(
      'agriculture',
      'Agriculture',
      'Agriculture DMRV',
      'Tracks soil carbon, crop management, fertilizer impacts, and methane or nitrous oxide signals.',
      ['Soil Samples', 'IoT Sensors', 'Management Data', 'Weather Data', 'Activity Data'],
      ['Soil organic carbon', 'N₂O / CH₄ emissions', 'Fertilizer impacts', 'Practice verification'],
    ),
    row(
      'grassland-savanna',
      'Grassland / Savanna',
      'Grassland / Savanna DMRV',
      'Evaluates biomass, grazing pressure, fire regimes, and rangeland condition.',
      ['Satellite Imagery', 'Field Surveys', 'Soil Samples', 'Fire Data', 'Grazing Data'],
      ['Biomass productivity', 'Soil carbon', 'Fire regime', 'Grazing intensity'],
    ),
    row(
      'soil-restoration',
      'Soil Restoration',
      'Soil Restoration DMRV',
      'Measures regenerative practices, erosion reduction, soil recovery, and carbon rebuilding.',
      ['Soil Samples', 'Drone Imagery', 'Erosion Maps', 'Moisture Data', 'Practice Records'],
      ['Soil recovery', 'Erosion reduction', 'Organic carbon gains', 'Restoration progress'],
    ),
    row(
      'peatland-boreal',
      'Peatland / Boreal',
      'Peatland / Boreal DMRV',
      'Tracks peat carbon, drainage, methane flux, fire risk, and rewetting outcomes.',
      ['Satellite Imagery', 'Soil Cores', 'Methane Sensors', 'Fire Data', 'Water Table Data'],
      ['Peat carbon stock', 'Methane emissions', 'Fire risk', 'Rewetting performance'],
    ),
    row(
      'afolu-land-carbon',
      'AFOLU',
      'AFOLU DMRV',
      'Integrates agriculture, forestry, and other land-use interventions in one verification pathway.',
      ['Satellite Imagery', 'Parcel Maps', 'Activity Records', 'Field Validation', 'Carbon Factors'],
      ['Multi-land-use accounting', 'Emission reductions', 'Removal estimates', 'Intervention tracking'],
    ),
    row(
      'redd-plus',
      'REDD+',
      'REDD+ DMRV',
      'Assesses avoided deforestation, forest protection, leakage risk, and conservation performance.',
      ['Satellite Imagery', 'Baseline Maps', 'Patrol Reports', 'Leakage Analysis', 'Community Records'],
      ['Avoided deforestation', 'Leakage risk', 'Forest integrity', 'Protection effectiveness'],
    ),
    row(
      'carbon-project-integrity',
      'Carbon Project Integrity',
      'Carbon Project Integrity DMRV',
      'Evaluates baseline quality, additionality, permanence, reversals, and double-counting risk.',
      ['Project Documents', 'Satellite Evidence', 'Baseline Data', 'Validator Review', 'Registry Records'],
      ['Additionality', 'Permanence risk', 'Double-counting checks', 'Claims integrity'],
    ),
  ],
  'water-blue-carbon': [
    row(
      'wetland-blue-carbon',
      'Wetland / Blue Carbon',
      'Wetland / Blue Carbon DMRV',
      'Assesses mangroves, saltmarshes, seagrass, peatlands, and inland wetland carbon and hydrology.',
      ['Satellite Imagery', 'Field Surveys', 'Sensor Stations', 'Tide Data', 'Biomass Data'],
      ['Extent / area change', 'Blue-carbon estimates', 'Hydrology indicators', 'Disturbance tracking'],
    ),
    row(
      'coastal-mangrove',
      'Coastal / Mangrove',
      'Coastal / Mangrove DMRV',
      'Monitors coastal protection, sediment dynamics, and blue-carbon sequestration.',
      ['Satellite Imagery', 'Drone Imagery', 'Tide Data', 'Field Plots', 'Sediment Data'],
      ['Mangrove extent', 'Sediment accretion', 'Protection services', 'Carbon stock trend'],
    ),
    row(
      'freshwater-watershed',
      'Freshwater / Watershed',
      'Freshwater / Watershed DMRV',
      'Evaluates watershed condition, stream networks, and basin-scale hydrologic indicators.',
      ['Satellite Imagery', 'Gauge Data', 'Land-Cover Maps', 'Rainfall Data', 'Field Samples'],
      ['Basin stress', 'Flow indicators', 'Land-use pressure', 'Water availability'],
    ),
    row(
      'marine-ocean',
      'Marine / Ocean',
      'Marine / Ocean DMRV',
      'Screens open-water and coastal ocean signals — plastics, chlorophyll, and stress indicators.',
      ['Hyperspectral Data', 'Ocean Color', 'PACE Metadata', 'AOI Maps', 'Alert Records'],
      ['Ocean stress', 'Plastic risk screening', 'Water quality context', 'Recovery trends'],
    ),
    row(
      'water-quality',
      'Water Quality',
      'Water Quality DMRV',
      'Measures nutrients, contaminants, and compliance-oriented water readings.',
      ['Lab Results', 'Sensor Feeds', 'Public Stations', 'Satellite Proxies', 'AOI'],
      ['Parameter exceedance', 'Trend vs baseline', 'Exposure context', 'Compliance evidence'],
    ),
    row(
      'water-treatment',
      'Water Treatment / Sanitation',
      'Water Treatment / Sanitation DMRV',
      'Tracks treatment performance, discharge context, and facility compliance evidence.',
      ['Permit Records', 'Discharge Monitoring', 'Facility Maps', 'Inspection Reports', 'Sensor Data'],
      ['Compliance context', 'Operational evidence', 'Discharge risk', 'Service gaps'],
    ),
    row(
      'flood-hydrology',
      'Flood / Hydrology',
      'Flood / Hydrology DMRV',
      'Structures flood extent, hydrologic anomalies, and civic flood intelligence — not official alerts.',
      ['Gauge Data', 'NWS / USGS', 'Satellite Flood Masks', 'Rainfall Data', 'Community Reports'],
      ['Flood stage', 'Exposure', 'Hydrology anomaly', 'Alert routing support'],
    ),
    row(
      'drought-water-stress',
      'Drought / Water Stress',
      'Drought / Water Stress DMRV',
      'Tracks drought indices, storage trends, and water-scarcity indicators.',
      ['Moisture Indices', 'Reservoir Records', 'GRACE / SMAP Proxies', 'Weather Data', 'AOI'],
      ['Moisture anomaly', 'Storage trend', 'Scarcity class', 'Stress duration'],
    ),
  ],
  'pollution-emissions': [
    row(
      'industrial-facility',
      'Industrial / Facility',
      'Industrial / Facility Emissions DMRV',
      'Evaluates stack emissions, process activity, energy use, and facility compliance evidence.',
      ['CEMS / Stack Data', 'Energy Meters', 'Thermal Imagery', 'Process Data', 'Compliance Records'],
      ['Direct emissions', 'Energy intensity', 'Fugitive leaks', 'Compliance evidence'],
    ),
    row(
      'air-quality',
      'Air Quality / Atmospheric',
      'Air Quality / Atmospheric DMRV',
      'Measures NO₂, ozone, methane, smoke, particulate matter, and plume movement.',
      ['Satellite Atmospherics', 'Air Sensors', 'Wind Data', 'Traffic Data', 'Alert Records'],
      ['Pollution concentration', 'Plume direction', 'Exposure trends', 'Air-quality alerts'],
    ),
    row(
      'methane-fugitive',
      'Methane Detection',
      'Methane Detection DMRV',
      'Tracks oil and gas leaks, landfill methane, agricultural methane, and hotspot persistence.',
      ['Satellite Imagery', 'Methane Sensors', 'Field Surveys', 'Infrared Data', 'Incident Records'],
      ['Leak hotspots', 'Methane persistence', 'Source attribution', 'Mitigation follow-up'],
    ),
    row(
      'regulatory-carb',
      'CARB / EPA Compliance',
      'CARB / EPA Compliance DMRV',
      'Compares reported emissions to external data, permits, and enforcement-relevant evidence.',
      ['Permit Records', 'Reported Emissions', 'Satellite Evidence', 'Facility Maps', 'Validator Review'],
      ['Reported vs observed', 'Permit alignment', 'Emissions discrepancy', 'Compliance risk'],
    ),
    row(
      'hazardous-waste',
      'Hazardous Waste',
      'Hazardous Waste DMRV',
      'Monitors waste handling, leak risks, manifests, and hazardous storage integrity.',
      ['Manifests', 'Storage Sensors', 'Site Imagery', 'Audit Records', 'Incident Reports'],
      ['Waste integrity', 'Leak / spill risk', 'Inventory gaps', 'Disposal compliance'],
    ),
    row(
      'waste-circular',
      'Waste / Circular Economy',
      'Waste / Circular Economy DMRV',
      'Tracks diversion, recycling performance, landfill burden, and waste-stream outcomes.',
      ['Facility Records', 'Collection Data', 'Landfill Sensors', 'Recycling Audits', 'Satellite Imagery'],
      ['Diversion rates', 'Landfill methane', 'Leakage / litter', 'Recycling verification'],
    ),
    row(
      'plastic-marine',
      'Plastic / Marine Debris',
      'Plastic / Marine Debris DMRV',
      'Detects floating plastics, shoreline debris, river discharge, and cleanup verification.',
      ['Hyperspectral Data', 'Drone Imagery', 'Cleanup Records', 'Shoreline Surveys', 'River Maps'],
      ['Plastic concentration', 'Debris movement', 'Cleanup effectiveness', 'Source pathways'],
    ),
    row(
      'toxic-exposure',
      'Toxic Exposure',
      'Toxic Exposure DMRV',
      'Assesses spills, contamination zones, toxic releases, and public risk indicators.',
      ['Soil / Water Samples', 'Exposure Maps', 'Health Reports', 'Incident Logs', 'Satellite Imagery'],
      ['Contamination zones', 'Toxic release risk', 'Exposure indicators', 'Escalation evidence'],
    ),
  ],
  'biodiversity-ecosystems': [
    row(
      'habitat-species',
      'Biodiversity / Habitat',
      'Biodiversity / Habitat DMRV',
      'Measures habitat integrity, species-support conditions, fragmentation, and ecosystem resilience.',
      ['Satellite Imagery', 'Habitat Maps', 'Species Surveys', 'Acoustic Sensors', 'Field Validation'],
      ['Habitat extent', 'Fragmentation', 'Species-support indicators', 'Ecosystem condition'],
    ),
    row(
      'protected-area',
      'Protected Area',
      'Protected Area DMRV',
      'Tracks reserve boundaries, encroachment, illegal disturbance, and conservation condition.',
      ['Boundary Maps', 'Patrol Reports', 'Satellite Alerts', 'Drone Imagery', 'Legal Records'],
      ['Encroachment risk', 'Disturbance events', 'Protection effectiveness', 'Boundary integrity'],
    ),
    row(
      'wildlife-corridor',
      'Wildlife Corridor',
      'Wildlife Corridor DMRV',
      'Evaluates connectivity, movement pathways, fragmentation, and corridor performance.',
      ['Land-Cover Maps', 'GPS Tracking', 'Camera Traps', 'Corridor Maps', 'Field Surveys'],
      ['Connectivity', 'Barrier pressure', 'Movement support', 'Corridor quality'],
    ),
    row(
      'coral-reef',
      'Coral Reef',
      'Coral Reef DMRV',
      'Monitors reef condition, bleaching signals, ocean stress, and recovery trends.',
      ['Satellite Imagery', 'Ocean Color', 'Dive Surveys', 'Temperature Data', 'Reef Maps'],
      ['Reef health', 'Bleaching risk', 'Water stress', 'Recovery trends'],
    ),
    row(
      'pollinator-ag',
      'Pollinator / Ag Biodiversity',
      'Pollinator / Agricultural Biodiversity DMRV',
      'Assesses pollinator habitat, farm biodiversity, and ecosystem-support practices.',
      ['Farm Records', 'Pollinator Surveys', 'Habitat Maps', 'Sensor Data', 'Field Photos'],
      ['Pollinator support', 'Habitat diversity', 'Practice verification', 'Ecosystem benefit'],
    ),
    row(
      'invasive-species',
      'Invasive Species',
      'Invasive Species DMRV',
      'Tracks invasive spread, ecosystem damage, containment actions, and risk zones.',
      ['Remote Sensing', 'Sightings Data', 'Field Surveys', 'Risk Maps', 'Control Records'],
      ['Spread zones', 'Damage indicators', 'Control effectiveness', 'Reinvasion risk'],
    ),
    row(
      'ecological-restoration',
      'Ecological Restoration',
      'Ecological Restoration DMRV',
      'Measures before/after restoration, habitat recovery, and intervention effectiveness.',
      ['Baseline Photos', 'Satellite Imagery', 'Intervention Records', 'Field Validation', 'Time-Series Maps'],
      ['Restoration progress', 'Habitat recovery', 'Intervention outcomes', 'Long-term resilience'],
    ),
    row(
      'nature-positive',
      'Nature Positive',
      'Nature Positive DMRV',
      'Evaluates net ecological gains, biodiversity claims, and overall ecosystem improvement.',
      ['Project Documents', 'Biodiversity Metrics', 'Satellite Evidence', 'Validator Review', 'Claims Records'],
      ['Net gain', 'Claims support', 'Biodiversity trend', 'Evidence confidence'],
    ),
  ],
  'climate-risk-disaster': [
    row(
      'wildfire',
      'Wildfire / Burn Scar',
      'Wildfire / Burn Scar DMRV',
      'Assesses burn severity, biomass loss, regrowth, and fire-recovery condition.',
      ['FIRMS Alerts', 'Burn Scar Imagery', 'Biomass Data', 'Field Surveys', 'Recovery Maps'],
      ['Burn severity', 'Biomass loss', 'Fire perimeter', 'Regrowth trend'],
    ),
    row(
      'heat-island',
      'Heat Island',
      'Heat Island DMRV',
      'Measures urban heat, canopy gaps, cooling infrastructure, and exposure hotspots.',
      ['Thermal Imagery', 'Canopy Maps', 'Air Temperature', 'Building Data', 'Field Validation'],
      ['Heat hotspots', 'Canopy deficit', 'Cooling benefit', 'Exposure intensity'],
    ),
    row(
      'climate-adaptation',
      'Climate Adaptation',
      'Climate Adaptation DMRV',
      'Evaluates flood defenses, cooling centers, green infrastructure, and adaptation outcomes.',
      ['Flood Maps', 'Infrastructure Records', 'Before/After Imagery', 'Project Records', 'Community Reports'],
      ['Adaptation performance', 'Risk reduction', 'Asset protection', 'Project effectiveness'],
    ),
    row(
      'disaster-recovery',
      'Disaster Recovery',
      'Disaster Recovery DMRV',
      'Tracks rebuilding progress after floods, fires, storms, or other major events.',
      ['Satellite Imagery', 'Damage Assessments', 'Project Records', 'Drone Imagery', 'Field Validation'],
      ['Recovery progress', 'Remaining damage', 'Restoration status', 'Reconstruction evidence'],
    ),
    row(
      'infrastructure-risk',
      'Infrastructure Risk',
      'Infrastructure Risk DMRV',
      'Monitors roads, bridges, drainage, slopes, and dangerous structural conditions.',
      ['Infrastructure Maps', 'Condition Surveys', 'Sensor Data', 'Incident Reports', 'Topography'],
      ['Structural risk', 'Drainage performance', 'Failure hotspots', 'Maintenance priority'],
    ),
    row(
      'insurance-risk',
      'Insurance Risk',
      'Insurance Risk DMRV',
      'Verifies hazard exposure, damage evidence, and site-level risk indicators.',
      ['Hazard Maps', 'Claim Records', 'Site Photos', 'Exposure Models', 'Satellite Imagery'],
      ['Damage evidence', 'Exposure level', 'Claim support', 'Insurable risk'],
    ),
    row(
      'community-resilience',
      'Community Resilience',
      'Community Resilience DMRV',
      'Assesses preparedness, shelters, local capacity, and vulnerability reduction.',
      ['Shelter Maps', 'Demographic Layers', 'Community Reports', 'Resource Records', 'Heat / Flood Maps'],
      ['Preparedness', 'Vulnerability reduction', 'Resource access', 'Community capacity'],
    ),
    row(
      'early-warning',
      'Early Warning',
      'Early Warning DMRV',
      'Tracks precursor signals, alerts, escalation indicators, and evidence for rapid response.',
      ['Sensor Feeds', 'Forecast Data', 'Satellite Alerts', 'Incident Logs', 'Escalation Rules'],
      ['Alert triggers', 'Signal confidence', 'Escalation timing', 'Response support'],
    ),
  ],
  'urban-energy-infrastructure': [
    row(
      'urban-built',
      'Urban / Built Environment',
      'Urban / Built Environment DMRV',
      'Evaluates urban form, green cover, building activity, and heat-island mitigation.',
      ['Satellite Imagery', 'Building Data', 'Land-Cover Maps', 'Mobility Data', 'Air Quality Data'],
      ['Green cover', 'Building intensity', 'Urban heat', 'Mobility context'],
    ),
    row(
      'renewable-energy',
      'Renewable Energy',
      'Renewable Energy DMRV',
      'Tracks solar, wind, storage, clean generation, and infrastructure performance.',
      ['Site Imagery', 'Generation Data', 'Utility Records', 'Equipment Data', 'Validator Review'],
      ['Generation output', 'Asset operation', 'Emissions reduction', 'Project verification'],
    ),
    row(
      'ev-mobility',
      'EV / Clean Mobility',
      'EV / Clean Mobility DMRV',
      'Monitors EV fleets, charging networks, mode shift, and emissions-reduction outcomes.',
      ['Charger Maps', 'Fleet Records', 'Mobility Data', 'Route Analytics', 'Energy Use'],
      ['Fleet electrification', 'Charger access', 'Mode shift', 'Mobility emissions'],
    ),
    row(
      'building-efficiency',
      'Building Efficiency',
      'Building Efficiency DMRV',
      'Measures energy use, retrofits, operational savings, and building-performance gains.',
      ['Energy Meters', 'Retrofit Records', 'Thermal Imagery', 'Building Records', 'Performance Reports'],
      ['Efficiency gains', 'Energy savings', 'Thermal performance', 'Retrofit evidence'],
    ),
    row(
      'smart-city',
      'Smart City',
      'Smart City DMRV',
      'Integrates sensors, traffic, air, service data, and urban condition signals.',
      ['Sensor Feeds', 'Traffic Data', 'Air Data', 'Service Logs', 'City Maps'],
      ['Urban signals', 'System status', 'Service quality', 'Operational awareness'],
    ),
    row(
      'transport-emissions',
      'Transportation Emissions',
      'Transportation Emissions DMRV',
      'Assesses fleet activity, congestion, movement patterns, and mobility emissions.',
      ['Fleet Data', 'Traffic Analytics', 'Fuel Use', 'Route Maps', 'Emissions Factors'],
      ['Congestion intensity', 'Fleet emissions', 'Movement trends', 'Mode profile'],
    ),
    row(
      'green-infrastructure',
      'Green Infrastructure',
      'Green Infrastructure DMRV',
      'Tracks trees, bioswales, permeable surfaces, and cooling or runoff benefits.',
      ['Canopy Maps', 'Stormwater Data', 'Surface Maps', 'Field Surveys', 'Project Records'],
      ['Cooling benefit', 'Runoff reduction', 'Green-asset condition', 'Project impact'],
    ),
    row(
      'public-works',
      'Public Works',
      'Public Works DMRV',
      'Verifies maintenance, repairs, service delivery, and project-completion evidence.',
      ['Work Orders', 'Site Photos', 'Project Maps', 'Inspection Reports', 'Completion Records'],
      ['Maintenance status', 'Repair evidence', 'Completion progress', 'Public service integrity'],
    ),
  ],
  'supply-chain-claims': [
    row(
      'supply-chain-traceability',
      'Supply Chain Traceability',
      'Supply Chain Traceability DMRV',
      'Verifies product origin, chain of custody, supplier records, and sourcing transparency.',
      ['Shipment Records', 'Supplier Data', 'QR Records', 'Audit Docs', 'Satellite Checks'],
      ['Origin proof', 'Chain of custody', 'Supplier verification', 'Traceability confidence'],
    ),
    row(
      'timber-deforestation-free',
      'Timber / Deforestation-Free',
      'Timber / Deforestation-Free DMRV',
      'Tracks logging risk, land conversion, and forest-linked commodity sourcing.',
      ['Forest Alerts', 'Parcel Maps', 'Supplier Records', 'Field Surveys', 'Compliance Docs'],
      ['Deforestation risk', 'Source-area integrity', 'Illegal logging risk', 'Sourcing evidence'],
    ),
    row(
      'mining-extractives',
      'Mining / Extractives',
      'Mining / Extractives DMRV',
      'Assesses mine disturbance, tailings integrity, reclamation, and water-risk evidence.',
      ['Satellite Imagery', 'Drone Imagery', 'Tailings Data', 'Water Quality', 'Reclamation Surveys'],
      ['Land disturbance', 'Tailings stability', 'Water risk', 'Reclamation progress'],
    ),
    row(
      'agricultural-commodity',
      'Agricultural Commodity',
      'Agricultural Commodity DMRV',
      'Verifies crop sourcing, land-use risk, and commodity-linked environmental performance.',
      ['Farm Maps', 'Supplier Records', 'Land-Use Checks', 'Harvest Data', 'Validator Review'],
      ['Commodity origin', 'Land-use risk', 'Practice verification', 'Sourcing integrity'],
    ),
    row(
      'corporate-esg',
      'Corporate ESG Claims',
      'Corporate ESG Claims DMRV',
      'Evaluates sustainability claims against evidence, records, and operational disclosures.',
      ['Reports', 'KPI Dashboards', 'Satellite Evidence', 'Audit Records', 'Claims Documents'],
      ['Claim support', 'Disclosure quality', 'Evidence alignment', 'Credibility level'],
    ),
    row(
      'greenwashing-detection',
      'Greenwashing Detection',
      'Greenwashing Detection DMRV',
      'Compares claims to satellite, permit, and field evidence to flag credibility risks.',
      ['Marketing Claims', 'Satellite Checks', 'Permit Records', 'Field Evidence', 'Risk Scoring'],
      ['Claim mismatch', 'Missing evidence', 'Greenwashing risk', 'Escalation priority'],
    ),
    row(
      'offset-integrity',
      'Offset Integrity',
      'Offset Integrity DMRV',
      'Assesses offset quality, permanence, double-counting risk, and claim alignment.',
      ['Registry Records', 'Project Docs', 'Baseline Data', 'Satellite Evidence', 'Validator Review'],
      ['Additionality', 'Permanence', 'Double-counting checks', 'Offset credibility'],
    ),
    row(
      'product-impact',
      'Product Impact',
      'Product Impact DMRV',
      'Measures product-level environmental footprint and supporting impact evidence.',
      ['Product Data', 'Lifecycle Inputs', 'Supply Records', 'Impact Metrics', 'Audit Evidence'],
      ['Product footprint', 'Impact evidence', 'Traceable inputs', 'Claims support'],
    ),
  ],
  'community-accountability': [
    row(
      'environmental-justice',
      'Environmental Justice',
      'Environmental Justice DMRV',
      'Measures pollution burden, facility proximity, vulnerability, and disproportionate community risk.',
      ['Census Layers', 'Facility Maps', 'Exposure Data', 'Community Reports', 'Satellite Imagery'],
      ['Burden hotspots', 'Proximity risk', 'Vulnerability context', 'Justice indicators'],
    ),
    row(
      'community-harm',
      'Community Harm',
      'Community Harm DMRV',
      'Tracks local complaints, exposure reports, unsafe conditions, and harm indicators.',
      ['Complaint Logs', 'Incident Photos', 'Field Reports', 'Risk Maps', 'Validator Review'],
      ['Harm patterns', 'Exposure reports', 'Severity signals', 'Follow-up need'],
    ),
    row(
      'public-health-environment',
      'Public Health Environment',
      'Public Health Environment DMRV',
      'Evaluates air, water, toxins, sanitation, and environment-linked health pressures.',
      ['Health Indicators', 'Water Quality', 'Air Sensors', 'Sanitation Records', 'Community Reports'],
      ['Health-linked risk', 'Environmental pressure', 'Service gaps', 'Public concern'],
    ),
    row(
      'school-housing-environment',
      'School / Housing Environment',
      'School / Housing Environment DMRV',
      'Assesses mold, lead, unsafe conditions, heat, and building health risks.',
      ['Building Inspections', 'Moisture Data', 'Heat Maps', 'Tenant Reports', 'Field Photos'],
      ['Indoor risk', 'Structural concerns', 'Exposure indicators', 'Habitability issues'],
    ),
    row(
      'neighborhood-safety',
      'Neighborhood Safety',
      'Neighborhood Safety DMRV',
      'Monitors hazards, road danger, lighting, public-space risk, and dangerous infrastructure.',
      ['Road Maps', 'Lighting Data', 'Incident Records', 'Site Photos', 'Infrastructure Maps'],
      ['Safety hotspots', 'Hazard presence', 'Infrastructure risk', 'Neighborhood alerts'],
    ),
    row(
      'public-complaint-verification',
      'Public Complaint Verification',
      'Public Complaint Verification DMRV',
      'Validates citizen reports against maps, records, and layered evidence.',
      ['Complaint Records', 'Satellite Checks', 'Facility Data', 'Site Photos', 'Verification Notes'],
      ['Report validation', 'Evidence matching', 'Escalation readiness', 'Trust score'],
    ),
    row(
      'qr-evidence-site',
      'QR Evidence Site',
      'QR Evidence Site DMRV',
      'Connects location-based reporting, QR pages, hashes, and site-level evidence chains.',
      ['QR Pages', 'Blockchain Hashes', 'Site Photos', 'Timestamp Logs', 'Document Records'],
      ['Evidence chain', 'Site traceability', 'Timestamp proof', 'Audit trail'],
    ),
    row(
      'mission-based-community',
      'Mission-Based Community',
      'Mission-Based Community DMRV',
      'Uses missions and community tasks to gather verified local evidence.',
      ['Mission Tasks', 'Mobile Reports', 'Geo Tags', 'Review Workflow', 'Reward Records'],
      ['Community participation', 'Task completion', 'Evidence quality', 'Mission outcomes'],
    ),
  ],
  'custom-intelligence': [
    row(
      'custom-framework',
      'Custom Project',
      'Custom Project DMRV',
      'Configures user-defined indicators, rules, and verification pathways.',
      ['User Inputs', 'Rules Engine', 'Custom Records', 'Config Files', 'Validator Review'],
      ['Flexible framework', 'User-defined indicators', 'Workflow control', 'Scalable configuration'],
    ),
    row(
      'ai-anomaly',
      'AI Anomaly Detection',
      'AI Anomaly Detection DMRV',
      'Flags unusual changes, suspicious claims, and high-risk evidence gaps.',
      ['Time-Series Data', 'AI Models', 'Risk Scoring', 'Alert Logs', 'Satellite Imagery'],
      ['Anomaly flags', 'Suspicious patterns', 'Evidence gaps', 'Risk escalation'],
    ),
    row(
      'blockchain-evidence',
      'Blockchain Evidence',
      'Blockchain Evidence DMRV',
      'Preserves hashes, timestamps, chain of custody, and immutable audit records.',
      ['Hash Records', 'Timestamp Logs', 'QR Pages', 'Evidence Files', 'Audit Trail'],
      ['Immutable proof', 'Chain of custody', 'Record integrity', 'Public verification'],
    ),
    row(
      'validator-review',
      'Validator Review',
      'Validator Review DMRV',
      'Supports human review, expert scoring, escalation, and final verification decisions.',
      ['Review Queue', 'Expert Notes', 'Scoring System', 'Decision Log', 'Escalation Routes'],
      ['Human verification', 'Review status', 'Expert confidence', 'Final decision'],
    ),
    row(
      'iot-sensor',
      'IoT Sensor',
      'IoT Sensor DMRV',
      'Integrates live sensor feeds, alert streams, device data, and time-series signals.',
      ['Sensor Feeds', 'Dashboards', 'Device Logs', 'Alert Rules', 'Time-Series Charts'],
      ['Live monitoring', 'Device status', 'Threshold alerts', 'Trend analysis'],
    ),
    row(
      'drone-verification',
      'Drone Verification',
      'Drone Verification DMRV',
      'Uses drone imagery, inspections, and site-level before/after evidence.',
      ['Drone Imagery', 'Flight Plans', 'Site Photos', 'Orthomaps', 'Inspection Logs'],
      ['Site verification', 'Before/after evidence', 'Visual confirmation', 'Survey coverage'],
    ),
    row(
      'satellite-fusion',
      'Satellite Fusion',
      'Satellite Fusion DMRV',
      'Combines multi-source imagery, time series, and cross-platform remote-sensing layers.',
      ['NASA Data', 'Copernicus Data', 'Landsat', 'Hyperspectral Layers', 'Change Maps'],
      ['Cross-source fusion', 'Time-series strength', 'Signal confidence', 'Remote-sensing depth'],
    ),
    row(
      'legal-evidence-packet',
      'Legal Evidence Packet',
      'Legal Evidence Packet DMRV',
      'Builds court-ready packets, exhibits, declarations, and QR-linked evidence sets.',
      ['Maps', 'Exhibits', 'Declarations', 'QR Evidence', 'Blockchain Proof'],
      ['Court-ready packet', 'Organized exhibits', 'Evidentiary chain', 'Verification support'],
    ),
  ],
};

export function getInfographicTypesForFamily(familyId: DmrvFamilyId): InfographicTypeSeed[] {
  return DMRV_INFOGRAPHIC_TYPES[familyId];
}

export function segmentColorForTypeIndex(index: number): string {
  return segmentColorForIndex(index);
}
