import type { AccountabilityModuleSignal } from '../shared/accountabilityModuleAdapters';
import { SatelliteConfidenceLevel, SatelliteEvidenceReadiness } from '../shared/satelliteIntelligenceTypes';

const PREVIEW = 'Preview scenario — not a live finding.';

/** Methane disclosure review — synthetic cross-module preview. */
export const sampleMethaneDisclosureSignals: AccountabilityModuleSignal[] = [
  {
    id: 'sample-m-1',
    moduleId: 'carb_emissions_audit',
    moduleLabel: 'CARB / Emissions Audit',
    moduleStatus: 'partial',
    providerIds: ['CARB_DATASET'],
    signalType: 'greenhouse_gas_hotspot',
    location: 'Example Facility A — preview coordinates withheld',
    aoi: '5 km buffer',
    observedDate: '2026-01-15',
    summary: `${PREVIEW} Official-record context for reported emissions vs investigation notes — potential mismatch wording only if records diverge.`,
    confidenceLevel: SatelliteConfidenceLevel.multi_source_supported,
    evidenceReadiness: SatelliteEvidenceReadiness.needs_validator_review,
    sourceSummary: 'Regulatory inventory cross-check (illustrative)',
    limitations: ['Not a determination of dishonesty'],
    warnings: ['Requires qualified analyst review.'],
    previewOnly: true,
  },
  {
    id: 'sample-m-2',
    moduleId: 'aquascan_water',
    moduleLabel: 'AquaScan / Water Monitor',
    moduleStatus: 'preview_only',
    providerIds: ['COPERNICUS'],
    signalType: 'water_quality_risk',
    location: 'Example Facility A',
    aoi: 'Adjacent water body',
    observedDate: '2026-01-15',
    summary: `${PREVIEW} Satellite-indicated water quality screening — field validation recommended.`,
    confidenceLevel: SatelliteConfidenceLevel.preview_only,
    evidenceReadiness: SatelliteEvidenceReadiness.needs_field_validation,
    sourceSummary: 'Workspace preview lane',
    limitations: ['No lab confirmation in preview'],
    warnings: [],
    previewOnly: true,
  },
];

/** Forest carbon project review — synthetic preview. */
export const sampleForestCarbonSignals: AccountabilityModuleSignal[] = [
  {
    id: 'sample-f-1',
    moduleId: 'forest_integrity',
    moduleLabel: 'Forest Integrity',
    moduleStatus: 'preview_only',
    providerIds: ['GEDI_LIDAR'],
    signalType: 'vegetation_decline',
    location: 'Example Forest Project B',
    aoi: 'Project polygon (preview)',
    observedDate: '2026-02-01',
    summary: `${PREVIEW} GEDI scaffold context — not live biomass product; potential mismatch with forest conservation claim requires multi-source review.`,
    confidenceLevel: SatelliteConfidenceLevel.preview_only,
    evidenceReadiness: SatelliteEvidenceReadiness.preview_only,
    sourceSummary: 'GEDI lane not fully implemented on default host (illustrative)',
    limitations: ['Does not invalidate carbon credits from satellite alone'],
    warnings: [],
    previewOnly: true,
  },
  {
    id: 'sample-f-2',
    moduleId: 'carbon_mrv',
    moduleLabel: 'Carbon DMRV',
    moduleStatus: 'preview_only',
    providerIds: ['LANDSAT_8_9'],
    signalType: 'carbon_mrv',
    location: 'Example Forest Project B',
    aoi: 'Project boundary',
    observedDate: '2026-02-01',
    summary: `${PREVIEW} DMRV workspace context — supports disclosure comparison, not final verification.`,
    confidenceLevel: SatelliteConfidenceLevel.preview_only,
    evidenceReadiness: SatelliteEvidenceReadiness.needs_field_validation,
    sourceSummary: 'Demo DMRV indicators',
    limitations: ['Local/demo mode must be labeled preview when APIs are cold'],
    warnings: [],
    previewOnly: true,
  },
];

/** Coastal water / plastic / algae — synthetic preview. */
export const sampleCoastalPlasticSignals: AccountabilityModuleSignal[] = [
  {
    id: 'sample-c-1',
    moduleId: 'plastic_watch',
    moduleLabel: 'Hyperspectral Plastic Watch',
    moduleStatus: 'metadata_only',
    providerIds: ['PACE_OCI'],
    signalType: 'plastic_pollution_confidence',
    location: 'Example Coastal Site C',
    aoi: '3 km coastal buffer',
    observedDate: '2026-03-10',
    summary: `${PREVIEW} PACE metadata / plastic confidence context — possible plastic or pollution confidence zone language only.`,
    confidenceLevel: SatelliteConfidenceLevel.metadata_only,
    evidenceReadiness: SatelliteEvidenceReadiness.needs_cross_dataset_comparison,
    sourceSummary: 'Metadata lane (illustrative)',
    limitations: ['Does not confirm plastic without field validation'],
    warnings: ['HAB and water confounders may mimic spectral anomalies.'],
    previewOnly: true,
  },
  {
    id: 'sample-c-2',
    moduleId: 'plastic_watch',
    moduleLabel: 'Hyperspectral Plastic Watch',
    moduleStatus: 'partial',
    providerIds: ['PACE_OCI'],
    signalType: 'harmful_algal_bloom_risk',
    location: 'Example Coastal Site C',
    aoi: '3 km coastal buffer',
    observedDate: '2026-03-10',
    summary: `${PREVIEW} Algae / HAB confounder screening — not a regulatory HAB determination.`,
    confidenceLevel: SatelliteConfidenceLevel.satellite_indicated,
    evidenceReadiness: SatelliteEvidenceReadiness.needs_field_validation,
    sourceSummary: 'Confounder panel (illustrative)',
    limitations: ['Field water sampling recommended'],
    warnings: [],
    previewOnly: true,
  },
];

/** Hazardous waste / pollution — synthetic preview. */
export const sampleHazardousWasteSignals: AccountabilityModuleSignal[] = [
  {
    id: 'sample-h-1',
    moduleId: 'hazardous_waste_audit',
    moduleLabel: 'Hazardous Waste / EPA',
    moduleStatus: 'preview_only',
    providerIds: ['EPA_DATASET'],
    signalType: 'hazardous_waste_risk',
    location: 'Example Industrial Site D',
    aoi: 'RCRA facility context',
    observedDate: '2026-04-05',
    summary: `${PREVIEW} RCRA-style record context — use “potential regulatory discrepancy” or requires review only when records support it.`,
    confidenceLevel: SatelliteConfidenceLevel.preview_only,
    evidenceReadiness: SatelliteEvidenceReadiness.needs_validator_review,
    sourceSummary: 'Imported or demo dataset mode (illustrative)',
    limitations: ['Does not infer illegal dumping'],
    warnings: [],
    previewOnly: true,
  },
  {
    id: 'sample-h-2',
    moduleId: 'envirofacts_geo',
    moduleLabel: 'EPA / Envirofacts Geo',
    moduleStatus: 'partial',
    providerIds: ['EPA_DATASET'],
    signalType: 'pollution_risk',
    location: 'Example Industrial Site D region',
    aoi: 'Map search AOI',
    observedDate: '2026-04-05',
    summary: `${PREVIEW} Public-record geographic baseline for cross-check.`,
    confidenceLevel: SatelliteConfidenceLevel.multi_source_supported,
    evidenceReadiness: SatelliteEvidenceReadiness.needs_cross_dataset_comparison,
    sourceSummary: 'Envirofacts family (illustrative)',
    limitations: ['Coverage gaps possible'],
    warnings: [],
    previewOnly: true,
  },
];
