import type { DpalBusinessUseCase, DpalBusinessUseCaseId } from './sourceTypes';

export const businessUseCaseMap: readonly DpalBusinessUseCase[] = [
  {
    id: 'carbon_credit_integrity',
    name: 'Carbon credit integrity screening',
    description: 'Cross-check MRV signals, public disclosures, and satellite proxies without asserting issuance or registry outcomes.',
    primaryClients: ['project_developers', 'buyers', 'auditors'],
    requiredSources: ['LANDSAT_8_9', 'NASA_HLS', 'GEDI_LIDAR', 'EPA_DATASET'],
    optionalSources: ['SENTINEL_2', 'SENTINEL_1', 'FIELD_SENSOR', 'LAB_SAMPLE', 'COMPANY_DISCLOSURE'],
    outputProducts: ['review_packet', 'screening_summary', 'limitations_appendix'],
    safetyLanguage:
      'Screening and evidence review only. No automatic carbon credit issuance, registry approval, or VIU eligibility.',
    validationRequired: true,
  },
  {
    id: 'corporate_greenwashing_review',
    name: 'Corporate greenwashing divergence review',
    description: 'Compare voluntary disclosures to independent environmental signals and public records.',
    primaryClients: ['investors', 'NGOs', 'media', 'legal_support'],
    requiredSources: ['COMPANY_DISCLOSURE', 'ESG_REPORT'],
    optionalSources: ['EPA_DATASET', 'SENTINEL_5P_TROPOMI', 'SENTINEL_2', 'WEATHER_DATA'],
    outputProducts: ['divergence_matrix', 'evidence_lane_index', 'review_packet'],
    safetyLanguage: 'Narrative and documentary comparison — not a finding of fraud or liability.',
    validationRequired: true,
  },
  {
    id: 'methane_super_emitter_monitoring',
    name: 'Methane super-emitter monitoring',
    description: 'Column and plume-oriented screening with transport context; commercial feeds optional.',
    primaryClients: ['operators', 'regulators', 'insurers', 'communities'],
    requiredSources: ['SENTINEL_5P_TROPOMI', 'WEATHER_DATA'],
    optionalSources: ['GHGSAT', 'TEMPO', 'CARB_DATASET', 'EPA_DATASET', 'FIELD_SENSOR'],
    outputProducts: ['plume_screening_log', 'limitations_memo', 'validator_request_template'],
    safetyLanguage: 'Anomaly screening requires validation; no enforcement or guilt conclusions.',
    validationRequired: true,
  },
  {
    id: 'co2_facility_verification',
    name: 'CO₂ facility verification context',
    description: 'Satellite column context plus inventories and meteorology — not stack testing.',
    primaryClients: ['facilities', 'auditors', 'governments'],
    requiredSources: ['WEATHER_DATA', 'EPA_DATASET'],
    optionalSources: ['OCO_3', 'OCO_2', 'SENTINEL_5P_TROPOMI', 'CARB_DATASET'],
    outputProducts: ['screening_summary', 'review_packet'],
    safetyLanguage: 'Column CO₂ cannot alone verify facility emissions without modeling and independent measurements.',
    validationRequired: true,
  },
  {
    id: 'harmful_algal_bloom_watch',
    name: 'Harmful algal bloom watch',
    description: 'Ocean color and thermal context for bloom risk triage in coastal and lake settings.',
    primaryClients: ['water_agencies', 'ports', 'tribes', 'utilities'],
    requiredSources: ['PACE_OCI', 'SENTINEL_3', 'WEATHER_DATA'],
    optionalSources: ['SENTINEL_2', 'VIIRS', 'FIELD_SENSOR', 'RIVER_TIDE_DATA'],
    outputProducts: ['bloom_screening_timeline', 'review_packet'],
    safetyLanguage: 'Remote sensing suggests conditions; field assays confirm toxicity and species.',
    validationRequired: true,
  },
  {
    id: 'plastic_pollution_watch',
    name: 'Plastic pollution watch',
    description: 'Coastal/ocean color proxies and vessel activity context — no polymer identification claim from color alone.',
    primaryClients: ['coastal_managers', 'NGOs', 'ports'],
    requiredSources: ['PACE_OCI', 'SENTINEL_2'],
    optionalSources: ['VIIRS', 'AIS_VESSEL_DATA', 'COMMUNITY_REPORT', 'DRONE_SURVEY'],
    outputProducts: ['screening_summary', 'evidence_lane_index'],
    safetyLanguage: 'Use “suggestive” language; high-resolution or field validation required for debris attribution.',
    validationRequired: true,
  },
  {
    id: 'blue_carbon_mrv',
    name: 'Blue carbon MRV context',
    description: 'Combine wetland extent, structure samples, and tide context for screening-level MRV inputs.',
    primaryClients: ['project_developers', 'governments'],
    requiredSources: ['SENTINEL_2', 'SWOT', 'WEATHER_DATA'],
    optionalSources: ['GEDI_LIDAR', 'ICESAT_2', 'NASA_HLS', 'FIELD_SENSOR', 'LAB_SAMPLE'],
    outputProducts: ['mrv_context_packet', 'limitations_appendix'],
    safetyLanguage: 'Not certified carbon stock; no automatic credit issuance.',
    validationRequired: true,
  },
  {
    id: 'forest_carbon_deforestation_audit',
    name: 'Forest carbon / deforestation audit',
    description: 'Optical/SAR change detection with biomass samples where available.',
    primaryClients: ['landowners', 'investors', 'governments'],
    requiredSources: ['LANDSAT_8_9', 'NASA_HLS', 'NASA_FIRMS'],
    optionalSources: ['SENTINEL_1', 'SENTINEL_2', 'GEDI_LIDAR', 'DYNAMIC_WORLD', 'PLANET_SCOPE'],
    outputProducts: ['disturbance_timeline', 'review_packet'],
    safetyLanguage: 'Disturbance screening is not legal land tenure or enforcement.',
    validationRequired: true,
  },
  {
    id: 'illegal_mining_land_disturbance',
    name: 'Illegal mining / land disturbance screening',
    description: 'SAR/optical disturbance flags with public records — intent and legality require investigation.',
    primaryClients: ['governments', 'NGOs', 'insurers'],
    requiredSources: ['SENTINEL_1', 'SENTINEL_2'],
    optionalSources: ['LANDSAT_8_9', 'NASA_EMIT', 'DRONE_SURVEY', 'EPA_DATASET', 'MAXAR_WORLDVIEW'],
    outputProducts: ['change_detection_memo', 'validator_request_template'],
    safetyLanguage: 'Use “disturbance detected”; no guilt, permit violation, or enforcement conclusions.',
    validationRequired: true,
  },
  {
    id: 'water_pollution_evidence',
    name: 'Water pollution evidence packet',
    description: 'Combine optical water indices, public discharge records, and lab/field validation hooks.',
    primaryClients: ['communities', 'utilities', 'legal_support'],
    requiredSources: ['EPA_DATASET', 'SENTINEL_2'],
    optionalSources: ['SENTINEL_3', 'FIELD_SENSOR', 'LAB_SAMPLE', 'RIVER_TIDE_DATA', 'INCIDENT_REPORT'],
    outputProducts: ['evidence_lane_index', 'review_packet'],
    safetyLanguage: 'Screening and record linkage — adjudication requires qualified experts.',
    validationRequired: true,
  },
  {
    id: 'flood_risk_damage_intelligence',
    name: 'Flood risk and damage intelligence',
    description: 'Hydrology context: SAR wetness, gauges, SWOT, weather windows — not an emergency dispatch system.',
    primaryClients: ['insurers', 'cities', 'NGOs'],
    requiredSources: ['WEATHER_DATA', 'RIVER_TIDE_DATA'],
    optionalSources: ['SENTINEL_1', 'SWOT', 'SMAP', 'VIIRS', 'COMMUNITY_REPORT'],
    outputProducts: ['flood_window_screening', 'limitations_memo'],
    safetyLanguage: 'Does not replace official warnings or legal flood determinations.',
    validationRequired: false,
  },
  {
    id: 'wildfire_illegal_burn_monitoring',
    name: 'Wildfire / illegal burn monitoring',
    description: 'Hotspot timelines with SAR/optical corroboration — arson or illegality not inferred automatically.',
    primaryClients: ['fire_agencies', 'insurers', 'land_managers'],
    requiredSources: ['NASA_FIRMS', 'WEATHER_DATA'],
    optionalSources: ['VIIRS', 'SENTINEL_2', 'SENTINEL_1', 'LANDSAT_8_9'],
    outputProducts: ['hotspot_timeline', 'review_packet'],
    safetyLanguage: 'Hotspots are not proof of cause, intent, or jurisdiction-specific illegality.',
    validationRequired: true,
  },
  {
    id: 'urban_heat_environmental_justice',
    name: 'Urban heat / environmental justice context',
    description: 'Thermal and land-cover screening with demographic overlays added downstream in workflows.',
    primaryClients: ['cities', 'NGOs', 'health_agencies'],
    requiredSources: ['LANDSAT_8_9', 'ECOSTRESS'],
    optionalSources: ['TEMPO', 'DYNAMIC_WORLD', 'WEATHER_DATA', 'FIELD_SENSOR'],
    outputProducts: ['heat_exposure_screening', 'limitations_memo'],
    safetyLanguage: 'Exposure screening is not clinical outcome proof.',
    validationRequired: false,
  },
  {
    id: 'industrial_air_pollution_watch',
    name: 'Industrial air pollution watch',
    description: 'NO₂ columns, TEMPO diurnal context, and facility registry linkage.',
    primaryClients: ['agencies', 'NGOs', 'ports'],
    requiredSources: ['SENTINEL_5P_TROPOMI', 'EPA_DATASET'],
    optionalSources: ['TEMPO', 'NASA_EMIT', 'CARB_DATASET', 'WEATHER_DATA'],
    outputProducts: ['screening_summary', 'review_packet'],
    safetyLanguage: 'Column abundances are not ground concentrations or permit violations alone.',
    validationRequired: true,
  },
  {
    id: 'port_shipping_pollution',
    name: 'Port and shipping pollution screening',
    description: 'Vessel activity, NO₂, ocean color turbidity proxies near ports.',
    primaryClients: ['ports', 'coastal_agencies', 'NGOs'],
    requiredSources: ['SENTINEL_5P_TROPOMI', 'SENTINEL_2'],
    optionalSources: ['AIS_VESSEL_DATA', 'PACE_OCI', 'TEMPO', 'WEATHER_DATA'],
    outputProducts: ['port_screening_memo', 'evidence_lane_index'],
    safetyLanguage: 'AIS gaps and atmospheric mixing limit attribution.',
    validationRequired: true,
  },
  {
    id: 'agriculture_carbon_water_efficiency',
    name: 'Agriculture carbon / water efficiency screening',
    description: 'Soil moisture, ET/thermal stress, and optical crop condition proxies.',
    primaryClients: ['growers', 'ag_finance', 'governments'],
    requiredSources: ['SMAP', 'LANDSAT_8_9'],
    optionalSources: ['NASA_HLS', 'ECOSTRESS', 'SENTINEL_2', 'WEATHER_DATA'],
    outputProducts: ['screening_summary', 'limitations_memo'],
    safetyLanguage: 'Agronomic decisions require local agronomy validation.',
    validationRequired: false,
  },
  {
    id: 'drought_groundwater_risk',
    name: 'Drought and groundwater stress screening',
    description: 'GRACE large-basin trends with moisture and weather context — not well-specific adjudication.',
    primaryClients: ['water_agencies', 'insurers', 'agencies'],
    requiredSources: ['GRACE_FO', 'WEATHER_DATA'],
    optionalSources: ['SMAP', 'LANDSAT_8_9', 'RIVER_TIDE_DATA', 'FIELD_SENSOR'],
    outputProducts: ['basin_trend_screening', 'limitations_memo'],
    safetyLanguage: 'GRACE cannot localize to individual wells; legal groundwater claims need dedicated studies.',
    validationRequired: false,
  },
  {
    id: 'biodiversity_habitat_integrity',
    name: 'Biodiversity / habitat integrity screening',
    description: 'Land-cover dynamics and structure samples — species richness needs ecological field survey.',
    primaryClients: ['governments', 'NGOs', 'project_developers'],
    requiredSources: ['DYNAMIC_WORLD', 'LANDSAT_8_9'],
    optionalSources: ['NASA_HLS', 'SENTINEL_2', 'GEDI_LIDAR', 'MODIS'],
    outputProducts: ['habitat_change_screening', 'review_packet'],
    safetyLanguage: 'Remote indices are not species inventories or regulatory biodiversity sign-offs.',
    validationRequired: true,
  },
  {
    id: 'infrastructure_subsidence_monitoring',
    name: 'Infrastructure subsidence monitoring',
    description: 'InSAR-capable sources and structure height references where available.',
    primaryClients: ['cities', 'insurers', 'utilities'],
    requiredSources: ['SENTINEL_1'],
    optionalSources: ['ICESAT_2', 'CAPELLA_SAR', 'ICEYE_SAR', 'MAXAR_WORLDVIEW', 'NISAR'],
    outputProducts: ['deformation_screening', 'limitations_memo'],
    safetyLanguage: 'Commercial SAR and future missions are gated; deformation screening requires expert QA.',
    validationRequired: true,
  },
  {
    id: 'dam_reservoir_river_integrity',
    name: 'Dam, reservoir, and river integrity context',
    description: 'Stage/discharge, SWOT, and SAR wetness for hydrologic anomaly triage.',
    primaryClients: ['operators', 'governments', 'insurers'],
    requiredSources: ['RIVER_TIDE_DATA', 'WEATHER_DATA'],
    optionalSources: ['SWOT', 'SENTINEL_1', 'SMAP', 'GRACE_FO'],
    outputProducts: ['hydrology_screening', 'review_packet'],
    safetyLanguage: 'Not a dam safety certification or regulatory sign-off.',
    validationRequired: true,
  },
  {
    id: 'insurance_environmental_risk',
    name: 'Insurance environmental risk context',
    description: 'Multi-hazard screening stack: flood, fire, heat, air, and subsidence leads.',
    primaryClients: ['insurers', 'brokers', 'asset_managers'],
    requiredSources: ['WEATHER_DATA', 'NASA_FIRMS'],
    optionalSources: ['SENTINEL_1', 'GRACE_FO', 'TEMPO', 'ICEYE_SAR', 'LANDSAT_8_9'],
    outputProducts: ['risk_context_memo', 'limitations_appendix'],
    safetyLanguage: 'Not underwriting, pricing, or legal advice.',
    validationRequired: false,
  },
  {
    id: 'real_estate_land_due_diligence',
    name: 'Real estate / land due diligence',
    description: 'Historical land change, subsidence hints, and environmental record proximity.',
    primaryClients: ['buyers', 'lenders', 'developers'],
    requiredSources: ['LANDSAT_8_9', 'EPA_DATASET'],
    optionalSources: ['DYNAMIC_WORLD', 'SENTINEL_1', 'MAXAR_WORLDVIEW', 'PLANET_SCOPE'],
    outputProducts: ['due_diligence_screening', 'limitations_memo'],
    safetyLanguage: 'Environmental due diligence requires qualified professionals and local records review.',
    validationRequired: true,
  },
  {
    id: 'hazardous_waste_integrity_audit',
    name: 'Hazardous waste integrity audit support',
    description: 'RCRA/ECHO-style registry context with field and lab validation hooks.',
    primaryClients: ['facilities', 'agencies', 'legal_support'],
    requiredSources: ['EPA_DATASET'],
    optionalSources: ['REGULATORY_FILING', 'DRONE_SURVEY', 'LAB_SAMPLE', 'INCIDENT_REPORT'],
    outputProducts: ['registry_crosswalk', 'review_packet'],
    safetyLanguage: 'Registry presence is not proof of current noncompliance; no enforcement conclusions.',
    validationRequired: true,
  },
  {
    id: 'supplier_environmental_watch',
    name: 'Supplier environmental watch',
    description: 'Disclosure + facility signals + optional commercial imagery.',
    primaryClients: ['procurement', 'brands', 'investors'],
    requiredSources: ['ESG_REPORT', 'EPA_DATASET'],
    optionalSources: ['COMPANY_DISCLOSURE', 'SENTINEL_5P_TROPOMI', 'AIS_VESSEL_DATA', 'QR_EVIDENCE'],
    outputProducts: ['supplier_screening_log', 'review_packet'],
    safetyLanguage: 'Supplier screening is not contractual certification.',
    validationRequired: true,
  },
  {
    id: 'government_transparency_dashboard',
    name: 'Government transparency dashboard',
    description: 'Aggregate public datasets and satellite context for civic intelligence dashboards.',
    primaryClients: ['governments', 'civic_tech', 'media'],
    requiredSources: ['EPA_DATASET', 'WEATHER_DATA'],
    optionalSources: ['CARB_DATASET', 'REGULATORY_FILING', 'RIVER_TIDE_DATA', 'INCIDENT_REPORT'],
    outputProducts: ['dataset_catalog', 'limitations_memo'],
    safetyLanguage: 'Dashboards surface records; they do not judge officials or establish liability.',
    validationRequired: false,
  },
  {
    id: 'community_environmental_reporting',
    name: 'Community environmental reporting',
    description: 'Triage community reports with corroborating sensors and imagery.',
    primaryClients: ['communities', 'NGOs', 'agencies'],
    requiredSources: ['COMMUNITY_REPORT'],
    optionalSources: ['INCIDENT_REPORT', 'QR_EVIDENCE', 'WEATHER_DATA', 'SENTINEL_2', 'FIELD_SENSOR'],
    outputProducts: ['triage_timeline', 'validator_request_template'],
    safetyLanguage: 'Community reports are pending verification until corroborated.',
    validationRequired: true,
  },
  {
    id: 'environmental_litigation_support',
    name: 'Environmental litigation support (evidence organization)',
    description: 'Structured evidence lanes for counsel workflows — DPAL does not provide legal advice.',
    primaryClients: ['law_firms', 'experts'],
    requiredSources: ['REGULATORY_FILING', 'EPA_DATASET'],
    optionalSources: ['LAB_SAMPLE', 'DRONE_SURVEY', 'INCIDENT_REPORT', 'LANDSAT_8_9', 'SENTINEL_1'],
    outputProducts: ['evidence_lane_index', 'chain_of_custody_checklist'],
    safetyLanguage: 'Organizational tool only; counsel determines admissibility and strategy.',
    validationRequired: true,
  },
  {
    id: 'investor_climate_risk_intelligence',
    name: 'Investor climate risk intelligence',
    description: 'Combine disclosures and physical hazard screening without security offering claims.',
    primaryClients: ['asset_managers', 'banks', 'insurers'],
    requiredSources: ['COMPANY_DISCLOSURE', 'WEATHER_DATA'],
    optionalSources: ['ESG_REPORT', 'GRACE_FO', 'NASA_FIRMS', 'SENTINEL_5P_TROPOMI'],
    outputProducts: ['risk_screening_memo', 'limitations_appendix'],
    safetyLanguage: 'Not investment advice; no forward performance or compliance guarantees.',
    validationRequired: false,
  },
  {
    id: 'municipal_climate_resilience',
    name: 'Municipal climate resilience screening',
    description: 'Heat, flood, drought, and air screening layers for planning context.',
    primaryClients: ['cities', 'utilities'],
    requiredSources: ['WEATHER_DATA', 'LANDSAT_8_9'],
    optionalSources: ['TEMPO', 'SWOT', 'SMAP', 'GRACE_FO', 'RIVER_TIDE_DATA'],
    outputProducts: ['resilience_screening_pack', 'limitations_memo'],
    safetyLanguage: 'Planning support only; engineering designs require licensed professionals.',
    validationRequired: false,
  },
  {
    id: 'dpal_verified_impact_units',
    name: 'DPAL verified impact units (governance-gated)',
    description: 'Placeholder lane for future governance products — no automatic VIU issuance.',
    primaryClients: ['internal_governance', 'partners'],
    requiredSources: ['QR_EVIDENCE', 'LAB_SAMPLE'],
    optionalSources: ['FIELD_SENSOR', 'INCIDENT_REPORT', 'SENTINEL_2'],
    outputProducts: ['governance_checklist', 'review_packet'],
    safetyLanguage: 'No automatic VIU eligibility, credits, or blockchain anchoring.',
    validationRequired: true,
  },
];

export const businessUseCaseById: Readonly<Record<DpalBusinessUseCaseId, DpalBusinessUseCase>> = Object.fromEntries(
  businessUseCaseMap.map((u) => [u.id, u]),
) as Readonly<Record<DpalBusinessUseCaseId, DpalBusinessUseCase>>;
