import type { DpalSource } from './sourceTypes';

/**
 * Master list of DPAL environmental sources — one row per `sourceId`.
 * Future and commercial sources stay honest: they do not run as live NASA/ESA free stack.
 */
export const dpalSourceRegistry: readonly DpalSource[] = [
  {
    sourceId: 'PACE_OCI',
    name: 'PACE / OCI ocean color',
    category: 'ocean_water',
    status: 'live',
    providerType: 'satellite_instrument',
    signals: ['ocean_color', 'chlorophyll', 'habs', 'plastic_debris_proxy'],
    resolutionNote: '1 km global coverage (OCI); sub-pixel coastal features need higher resolution partners.',
    temporalNote: 'Near-daily revisits; cloud cover limits valid observations.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['harmful_algal_bloom_watch', 'plastic_pollution_watch', 'port_shipping_pollution', 'blue_carbon_mrv'],
    evidenceRole: 'Ocean color screening and anomaly context for blooms and turbidity — not proof of plastic mass.',
    confidenceRole: 'Supports medium confidence only with corroborating field or high-res imagery.',
    limitations: [
      'Ocean color retrievals are influenced by atmosphere, sun glint, and adjacency effects.',
      'Plastic debris is not uniquely identified at OCI native resolution; use “suggestive” language only.',
    ],
    safetyRules: ['no_auto_human_verify', 'no_blockchain_claim', 'no_legal_conclusion'],
    docsUrl: 'https://pace.gsfc.nasa.gov/',
  },
  {
    sourceId: 'SWOT',
    name: 'SWOT KaRIn surface water topography',
    category: 'ocean_water',
    status: 'live',
    providerType: 'satellite_mission',
    signals: ['water_surface_height', 'wet_extent'],
    resolutionNote: 'Coarse to moderate along-track spacing; best for large water bodies and floodplains.',
    temporalNote: '21-day repeat; not continuous monitoring.',
    requiredInputs: ['lat', 'lng', 'dateRange', 'aoiOptional'],
    businessUseCases: ['flood_risk_damage_intelligence', 'dam_reservoir_river_integrity', 'drought_groundwater_risk'],
    evidenceRole: 'Surface water extent / slope context for hydrology screening.',
    confidenceRole: 'Stronger when combined with gauges, SAR wetness, and hydrological models.',
    limitations: ['Vegetated wetlands and urban channels complicate height interpretation.', 'Not a legal flood determination.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion'],
    docsUrl: 'https://swot.jpl.nasa.gov/',
  },
  {
    sourceId: 'SENTINEL_2',
    name: 'Sentinel-2 MSI',
    category: 'ocean_water',
    status: 'live',
    providerType: 'satellite_instrument',
    signals: ['ndvi', 'ndwi', 'chlorophyll', 'land_cover_change'],
    resolutionNote: '10–20 m depending on product; scene-based.',
    temporalNote: '5-day revisit at equator (two satellites).',
    requiredInputs: ['lat', 'lng', 'dateRange', 'cloudMasking'],
    businessUseCases: [
      'plastic_pollution_watch',
      'water_pollution_evidence',
      'agriculture_carbon_water_efficiency',
      'biodiversity_habitat_integrity',
      'illegal_mining_land_disturbance',
    ],
    evidenceRole: 'Optical change detection and vegetation/water indices for screening.',
    confidenceRole: 'Increases with multi-temporal stacks and field validation.',
    limitations: ['Clouds and shadows block surface signal.', 'Cannot detect dissolved pollutants directly.'],
    safetyRules: ['no_auto_human_verify', 'no_carbon_credit_claim'],
    docsUrl: 'https://sentinel.esa.int/web/sentinel/missions/sentinel-2',
  },
  {
    sourceId: 'SENTINEL_3',
    name: 'Sentinel-3 OLCI / SLSTR',
    category: 'ocean_water',
    status: 'live',
    providerType: 'satellite_mission',
    signals: ['ocean_color', 'chlorophyll', 'thermal_stress'],
    resolutionNote: '300 m (OLCI) ocean color; coarser thermal.',
    temporalNote: 'Daily to two-day coverage depending on latitude.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['harmful_algal_bloom_watch', 'port_shipping_pollution', 'water_pollution_evidence'],
    evidenceRole: 'Synoptic ocean color for bloom and sediment screening.',
    confidenceRole: 'Moderate alone; better with in-situ chlorophyll or HAB assays.',
    limitations: ['Coastal adjacency and mixed pixels reduce fidelity near shore.', 'Thermal channels are not substitute for ECOSTRESS/Landsat TIR analytics.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion'],
    docsUrl: 'https://sentinel.esa.int/web/sentinel/missions/sentinel-3',
  },
  {
    sourceId: 'LANDSAT_8_9',
    name: 'Landsat 8/9 OLI + TIRS',
    category: 'forest_carbon',
    status: 'live',
    providerType: 'satellite_mission',
    signals: ['ndvi', 'ndwi', 'thermal_stress', 'land_cover_change'],
    resolutionNote: '30 m multispectral; 100 m TIRS (resampled products vary).',
    temporalNote: '16-day revisit per satellite.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: [
      'forest_carbon_deforestation_audit',
      'illegal_mining_land_disturbance',
      'urban_heat_environmental_justice',
      'agriculture_carbon_water_efficiency',
    ],
    evidenceRole: 'Long archive change detection and land surface temperature context.',
    confidenceRole: 'High for land-cover change when cloud-free pairs exist; not standalone for emissions.',
    limitations: ['Moderate resolution misses narrow disturbances.', 'Thermal products need careful atmospheric compensation.'],
    safetyRules: ['no_auto_human_verify', 'no_carbon_credit_claim'],
    docsUrl: 'https://www.usgs.gov/landsat-missions',
  },
  {
    sourceId: 'NASA_HLS',
    name: 'NASA Harmonized Landsat Sentinel-2',
    category: 'forest_carbon',
    status: 'live',
    providerType: 'derived_product',
    signals: ['ndvi', 'ndwi', 'land_cover_change'],
    resolutionNote: '30 m surface reflectance composite.',
    temporalNote: 'Near-weekly clear-sky composites at many latitudes.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['forest_carbon_deforestation_audit', 'agriculture_carbon_water_efficiency', 'biodiversity_habitat_integrity'],
    evidenceRole: 'Analysis-ready optical time series for disturbance screening.',
    confidenceRole: 'Improves confidence versus single-scene picks when compositing succeeds.',
    limitations: ['Composite artifacts near clouds/shadow edges.', 'Not a biomass inventory without lidar calibration.'],
    safetyRules: ['no_auto_human_verify', 'no_carbon_credit_claim'],
    docsUrl: 'https://hls.gsfc.nasa.gov/',
  },
  {
    sourceId: 'VIIRS',
    name: 'VIIRS (Suomi NPP / NOAA-20)',
    category: 'ocean_water',
    status: 'live',
    providerType: 'satellite_instrument',
    signals: ['active_fire', 'ocean_color', 'chlorophyll'],
    resolutionNote: '375–750 m depending on band/product.',
    temporalNote: 'Daily global coverage.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['wildfire_illegal_burn_monitoring', 'harmful_algal_bloom_watch', 'port_shipping_pollution'],
    evidenceRole: 'Large-area hotspot and coarse ocean color context.',
    confidenceRole: 'Good for early anomaly triage; weak for fine-scale liability.',
    limitations: ['Coarse resolution limits small-fire and narrow discharge detection.', 'Nighttime lights and bloom retrievals need expert QA.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion'],
    docsUrl: 'https://www.jpss.noaa.gov/viirs.html',
  },
  {
    sourceId: 'MODIS',
    name: 'MODIS Terra/Aqua',
    category: 'forest_carbon',
    status: 'historical',
    providerType: 'satellite_instrument',
    signals: ['ndvi', 'active_fire', 'thermal_stress'],
    resolutionNote: '250–1000 m products.',
    temporalNote: 'Daily; long historical archive.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['wildfire_illegal_burn_monitoring', 'drought_groundwater_risk', 'biodiversity_habitat_integrity'],
    evidenceRole: 'Historical trend context and active fire screening.',
    confidenceRole: 'Moderate for trends; limited for asset-scale decisions.',
    limitations: ['Aqua mission ended; continuity depends on product lineage.', 'Coarse pixels mix land covers.'],
    safetyRules: ['no_auto_human_verify', 'no_carbon_credit_claim'],
    docsUrl: 'https://modis.gsfc.nasa.gov/',
  },
  {
    sourceId: 'GEDI_LIDAR',
    name: 'GEDI canopy height / structure',
    category: 'forest_carbon',
    status: 'live',
    providerType: 'satellite_instrument',
    signals: ['biomass_height', 'forest_loss'],
    resolutionNote: '25 m footprints along ISS orbit tracks — spatially discontinuous.',
    temporalNote: 'ISS-based sampling, not wall-to-wall coverage.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['forest_carbon_deforestation_audit', 'blue_carbon_mrv', 'carbon_credit_integrity'],
    evidenceRole: 'Vertical structure samples to constrain biomass models.',
    confidenceRole: 'High locally when shots intersect AOI; low where tracks miss.',
    limitations: ['Non-contiguous coverage; extrapolation requires modeling.', 'Biomass estimates need field plots for calibration.'],
    safetyRules: ['no_auto_human_verify', 'no_carbon_credit_claim', 'no_viu_claim'],
    docsUrl: 'https://gedi.umd.edu/',
  },
  {
    sourceId: 'ESA_BIOMASS',
    name: 'ESA Biomass mission (BIOMASS)',
    category: 'forest_carbon',
    status: 'future',
    providerType: 'future_mission',
    signals: ['biomass_map'],
    resolutionNote: 'P-band SAR designed for biomass mapping (planned performance).',
    temporalNote: 'Mission-specific repeat once launched.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['forest_carbon_deforestation_audit', 'carbon_credit_integrity'],
    evidenceRole: 'Future wall-to-wall biomass-oriented SAR (not available as live DPAL provider yet).',
    confidenceRole: 'Must not contribute runtime confidence until live.',
    limitations: ['Not operational in DPAL live stack until launched and ingested.', 'Policy and processing choices still TBD globally.'],
    safetyRules: ['no_auto_human_verify', 'future_mission_gate'],
    docsUrl: 'https://www.esa.int/Applications/Observing_the_Earth/Biomass',
  },
  {
    sourceId: 'SENTINEL_1',
    name: 'Sentinel-1 C-SAR',
    category: 'forest_carbon',
    status: 'live',
    providerType: 'satellite_instrument',
    signals: ['sar_flood', 'sar_deformation', 'land_cover_change'],
    resolutionNote: '5–20 m IW/EW modes.',
    temporalNote: '6-day revisit at mid-latitudes (two satellites).',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: [
      'flood_risk_damage_intelligence',
      'illegal_mining_land_disturbance',
      'infrastructure_subsidence_monitoring',
      'port_shipping_pollution',
    ],
    evidenceRole: 'SAR change detection for surface water, disturbance, and deformation screening.',
    confidenceRole: 'Strong for change timing; interpretation needs ground control for material attribution.',
    limitations: ['Speckle and geometry effects require careful processing.', 'Does not identify chemical composition.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion'],
    docsUrl: 'https://sentinel.esa.int/web/sentinel/missions/sentinel-1',
  },
  {
    sourceId: 'ICESAT_2',
    name: 'ICESat-2 ATLAS photon lidar',
    category: 'forest_carbon',
    status: 'live',
    providerType: 'satellite_mission',
    signals: ['biomass_height'],
    resolutionNote: 'Along-track photon profiles; narrow ground tracks.',
    temporalNote: '91-day repeat; under-sampling in small AOIs.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['forest_carbon_deforestation_audit', 'blue_carbon_mrv', 'infrastructure_subsidence_monitoring'],
    evidenceRole: 'Elevation and canopy height samples for change analysis.',
    confidenceRole: 'High along tracks; requires spatial aggregation for AOI summaries.',
    limitations: ['Clouds affect signal; small AOIs may lack intersecting tracks.', 'Not a standalone carbon stock certification.'],
    safetyRules: ['no_auto_human_verify', 'no_carbon_credit_claim'],
    docsUrl: 'https://icesat-2.gsfc.nasa.gov/',
  },
  {
    sourceId: 'NASA_FIRMS',
    name: 'NASA FIRMS active fire detections',
    category: 'forest_carbon',
    status: 'live',
    providerType: 'public_agency_dataset',
    signals: ['active_fire'],
    resolutionNote: 'Sensor-dependent (MODIS/VIIRS/SNR).',
    temporalNote: 'Near real-time to daily updates.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['wildfire_illegal_burn_monitoring', 'forest_carbon_deforestation_audit', 'insurance_environmental_risk'],
    evidenceRole: 'Hotspot timeline for fire and burn anomaly triage.',
    confidenceRole: 'Moderate — confirm with SAR/cloud-free optical and field reports.',
    limitations: ['False positives from industrial flares and sun glint.', 'Does not prove intent or illegality.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion'],
    docsUrl: 'https://firms.modaps.eosdis.nasa.gov/',
  },
  {
    sourceId: 'NASA_EMIT',
    name: 'EMIT imaging spectroscopy (mineral/dust)',
    category: 'atmosphere_emissions',
    status: 'live',
    providerType: 'satellite_instrument',
    signals: ['dust_mineral_proxy'],
    resolutionNote: '60 m ISS-track coverage strips.',
    temporalNote: 'Non-global continuous coverage; AOI-dependent availability.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['industrial_air_pollution_watch', 'port_shipping_pollution', 'illegal_mining_land_disturbance'],
    evidenceRole: 'Surface mineralogy and dust-related screening where scenes exist.',
    confidenceRole: 'Medium when collocated with ground sampling; low if strips miss AOI.',
    limitations: ['Coverage gaps; not a direct trace-gas column instrument.', 'Results are material indicators, not facility permits.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion'],
    docsUrl: 'https://earth.jpl.nasa.gov/emit/',
  },
  {
    sourceId: 'SENTINEL_5P_TROPOMI',
    name: 'Sentinel-5P TROPOMI trace gases',
    category: 'atmosphere_emissions',
    status: 'live',
    providerType: 'satellite_instrument',
    signals: ['methane_column', 'co2_total_column', 'no2_so2'],
    resolutionNote: '5.5 km × 3.5 km to 7 km × 3.5 km depending on product era.',
    temporalNote: 'Daily global coverage.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['methane_super_emitter_monitoring', 'industrial_air_pollution_watch', 'co2_facility_verification'],
    evidenceRole: 'Column abundance screening for plumes and regional gradients.',
    confidenceRole: 'Plume detection benefits from wind fields and repeated overpasses; not facility-level permitting proof.',
    limitations: ['Column retrievals mix altitudes; surface concentrations differ.', 'Clouds degrade quality flags.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion', 'no_carbon_credit_claim'],
    docsUrl: 'https://sentinel.esa.int/web/sentinel/missions/sentinel-5p',
  },
  {
    sourceId: 'TEMPO',
    name: 'TEMPO geostationary air quality (NO2)',
    category: 'atmosphere_emissions',
    status: 'live',
    providerType: 'satellite_instrument',
    signals: ['air_quality_geostationary', 'no2_so2'],
    resolutionNote: 'North America field of regard; hourly daytime.',
    temporalNote: 'Hourly during daylight.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['industrial_air_pollution_watch', 'urban_heat_environmental_justice', 'port_shipping_pollution'],
    evidenceRole: 'Diurnal NO2 patterns for industrial and urban screening.',
    confidenceRole: 'Strong for temporal anomalies; weaker for absolute emissions quantification without models.',
    limitations: ['North America only; not global.', 'Column NO2 is not direct ground concentration.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion'],
    docsUrl: 'https://tempo.si.edu/',
  },
  {
    sourceId: 'SENTINEL_4',
    name: 'Sentinel-4 UVN imaging spectrometer (MTG)',
    category: 'atmosphere_emissions',
    status: 'future',
    providerType: 'future_mission',
    signals: ['air_quality_geostationary', 'no2_so2'],
    resolutionNote: 'Geostationary air quality over Europe/Africa (planned operations).',
    temporalNote: 'Frequent scans once fully operational in DPAL ingestion.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['industrial_air_pollution_watch'],
    evidenceRole: 'Future geostationary trace gas context for European domain.',
    confidenceRole: 'Excluded from live confidence until ingested.',
    limitations: ['Must not be treated as live DPAL provider until mission data is wired.', 'Regional coverage only.'],
    safetyRules: ['future_mission_gate', 'no_auto_human_verify'],
    docsUrl: 'https://sentinel.esa.int/web/sentinel/missions/sentinel-4',
  },
  {
    sourceId: 'OCO_2',
    name: 'OCO-2 CO₂ column',
    category: 'atmosphere_emissions',
    status: 'historical',
    providerType: 'satellite_mission',
    signals: ['co2_total_column'],
    resolutionNote: '1.3 × 2.25 km along-track snapshots; narrow swath.',
    temporalNote: '16-day repeat; sparse spatial sampling.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['co2_facility_verification', 'carbon_credit_integrity'],
    evidenceRole: 'XCO₂ screening where soundings intersect AOI.',
    confidenceRole: 'Low to medium for point sources; better for regional aggregation with models.',
    limitations: ['Sounding gaps; XCO₂ alone cannot attribute emissions to a facility without transport modeling.', 'Operational status varies by downstream product.'],
    safetyRules: ['no_auto_human_verify', 'no_carbon_credit_claim'],
    docsUrl: 'https://ocov2.jpl.nasa.gov/',
  },
  {
    sourceId: 'OCO_3',
    name: 'OCO-3 CO₂ snapshot mapping (ISS)',
    category: 'atmosphere_emissions',
    status: 'live',
    providerType: 'satellite_mission',
    signals: ['co2_total_column'],
    resolutionNote: 'Snapshot mapping mode improves spatial context vs OCO-2 in limited campaigns.',
    temporalNote: 'ISS orbit constraints; variable AOI cadence.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['co2_facility_verification', 'carbon_credit_integrity'],
    evidenceRole: 'Mapped XCO₂ context over urban/industrial targets when available.',
    confidenceRole: 'Medium with meteorology and inventory reconciliation; not permit-grade alone.',
    limitations: ['Clouds and aerosols degrade retrievals.', 'Attribution requires additional evidence.'],
    safetyRules: ['no_auto_human_verify', 'no_carbon_credit_claim'],
    docsUrl: 'https://ocov3.jpl.nasa.gov/',
  },
  {
    sourceId: 'GOSAT',
    name: 'GOSAT greenhouse gas observations',
    category: 'atmosphere_emissions',
    status: 'historical',
    providerType: 'satellite_mission',
    signals: ['co2_total_column', 'methane_column'],
    resolutionNote: '10 km footprint soundings.',
    temporalNote: 'Long archive; coarse spatial density.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['methane_super_emitter_monitoring', 'co2_facility_verification'],
    evidenceRole: 'Archive column greenhouse gas context.',
    confidenceRole: 'Weak for fine-scale plumes; useful for regional baselines.',
    limitations: ['Large footprint mixes sources.', 'Operational availability depends on partner processing.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion'],
    docsUrl: 'https://www.nies.go.jp/EN/igdb/index.html',
  },
  {
    sourceId: 'GOSAT_GW',
    name: 'GOSAT-GW (methane-focused successor path)',
    category: 'atmosphere_emissions',
    status: 'future',
    providerType: 'future_mission',
    signals: ['methane_column'],
    resolutionNote: 'Planned improved methane monitoring (follow JAXA program documentation).',
    temporalNote: 'Post-launch operations TBD for DPAL ingestion.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['methane_super_emitter_monitoring'],
    evidenceRole: 'Reserved for future JAXA methane products once live in DPAL.',
    confidenceRole: 'Must not increase confidence until status becomes live.',
    limitations: ['Not available as a DPAL live provider until mission data is integrated.'],
    safetyRules: ['future_mission_gate'],
    docsUrl: 'https://www.jaxa.jp/',
  },
  {
    sourceId: 'CO2M_FUTURE',
    name: 'CO2M / European CO₂ monitoring constellation (future)',
    category: 'atmosphere_emissions',
    status: 'future',
    providerType: 'future_mission',
    signals: ['co2_total_column', 'methane_column'],
    resolutionNote: 'Designed for anthropogenic CO₂ monitoring at city/plume scales.',
    temporalNote: 'Mission schedule dependent.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['co2_facility_verification', 'methane_super_emitter_monitoring', 'municipal_climate_resilience'],
    evidenceRole: 'Future high-value column monitoring — not runnable today.',
    confidenceRole: 'Excluded until live.',
    limitations: ['No live DPAL execution until launch and ingestion pipelines exist.'],
    safetyRules: ['future_mission_gate', 'no_carbon_credit_claim'],
    docsUrl: 'https://www.esa.int/Applications/Observing_the_Earth/CO2M',
  },
  {
    sourceId: 'CARBON_MAPPER_TANAGER',
    name: 'Carbon Mapper / Tanager hyperspectral path',
    category: 'atmosphere_emissions',
    status: 'partner_required',
    providerType: 'satellite_mission',
    signals: ['methane_column', 'dust_mineral_proxy'],
    resolutionNote: 'Planned high-resolution methane-capable imaging spectroscopy programs.',
    temporalNote: 'Partner data access and licensing required.',
    requiredInputs: ['lat', 'lng', 'dateRange', 'partnerAgreement'],
    businessUseCases: ['methane_super_emitter_monitoring', 'industrial_air_pollution_watch'],
    evidenceRole: 'Potential plume-grade screening when partner feeds are licensed.',
    confidenceRole: 'Cannot increase confidence without executed partner pipeline.',
    limitations: ['Commercial/partner licensing and API contracts required.', 'Not a public free stack default.'],
    safetyRules: ['partner_gate', 'no_auto_human_verify'],
    docsUrl: 'https://carbonmapper.org/',
  },
  {
    sourceId: 'GHGSAT',
    name: 'GHGSat commercial methane monitoring',
    category: 'atmosphere_emissions',
    status: 'commercial',
    providerType: 'commercial_imagery',
    signals: ['methane_column'],
    resolutionNote: 'High-resolution targeted methane plume products.',
    temporalNote: 'Tasking-dependent revisits.',
    requiredInputs: ['lat', 'lng', 'dateRange', 'commercialKey'],
    businessUseCases: ['methane_super_emitter_monitoring', 'supplier_environmental_watch', 'insurance_environmental_risk'],
    evidenceRole: 'Commercial plume screening where purchased and delivered.',
    confidenceRole: 'Can be high for plume detection when delivered; excluded from free-stack confidence.',
    limitations: ['Requires commercial contract and tasking budget.', 'Not interchangeable with public column products.'],
    safetyRules: ['commercial_gate', 'no_auto_human_verify', 'no_carbon_credit_claim'],
    docsUrl: 'https://www.ghgsat.com/',
  },
  {
    sourceId: 'NISAR',
    name: 'NASA-ISRO NISAR L-band SAR',
    category: 'heat_land',
    status: 'future',
    providerType: 'future_mission',
    signals: ['sar_deformation', 'forest_loss'],
    resolutionNote: 'Designed for deformation and ecosystem structure (L-band).',
    temporalNote: 'Science operations post-launch; DPAL ingestion TBD.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['infrastructure_subsidence_monitoring', 'forest_carbon_deforestation_audit', 'illegal_mining_land_disturbance'],
    evidenceRole: 'Future SAR backbone for disturbance and deformation — gated until live.',
    confidenceRole: 'Excluded until live.',
    limitations: ['Must not run as live provider until mission products are available to DPAL adapters.'],
    safetyRules: ['future_mission_gate'],
    docsUrl: 'https://nisar.jpl.nasa.gov/',
  },
  {
    sourceId: 'ECOSTRESS',
    name: 'ECOSTRESS land surface temperature / evapotranspiration',
    category: 'heat_land',
    status: 'live',
    providerType: 'satellite_instrument',
    signals: ['thermal_stress'],
    resolutionNote: '38 m TIR swaths under ISS orbit.',
    temporalNote: 'Irregular revisit by latitude.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['urban_heat_environmental_justice', 'drought_groundwater_risk', 'agriculture_carbon_water_efficiency'],
    evidenceRole: 'High-resolution thermal stress and ET-related screening where scenes exist.',
    confidenceRole: 'Medium-high locally; requires validation against weather stations for absolute accuracy.',
    limitations: ['Swath gaps; cloud contamination rules apply.', 'ET products need model context.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion'],
    docsUrl: 'https://ecostress.jpl.nasa.gov/',
  },
  {
    sourceId: 'CHIME_FUTURE',
    name: 'CHIME (surface biology/geology imaging spectrometer path, future)',
    category: 'heat_land',
    status: 'future',
    providerType: 'future_mission',
    signals: ['dust_mineral_proxy', 'land_cover_change'],
    resolutionNote: 'Planned imaging spectroscopy at moderate resolution.',
    temporalNote: 'Mission-dependent.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['biodiversity_habitat_integrity', 'illegal_mining_land_disturbance'],
    evidenceRole: 'Future spectroscopy layer — not runnable.',
    confidenceRole: 'Excluded until live.',
    limitations: ['No operational DPAL adapter until mission data policy and pipelines are defined.'],
    safetyRules: ['future_mission_gate'],
    docsUrl: 'https://earth.jpl.nasa.gov/chime/',
  },
  {
    sourceId: 'LSTM_FUTURE',
    name: 'Land Surface Temperature Monitoring (future ESA LSTM)',
    category: 'heat_land',
    status: 'future',
    providerType: 'future_mission',
    signals: ['thermal_stress'],
    resolutionNote: 'Planned geostationary thermal monitoring over Europe/Africa scope.',
    temporalNote: 'Future operational cadence.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['urban_heat_environmental_justice', 'drought_groundwater_risk'],
    evidenceRole: 'Future thermal monitoring context — gated.',
    confidenceRole: 'Excluded until live.',
    limitations: ['Regional scope; not global.', 'Not available in DPAL live stack yet.'],
    safetyRules: ['future_mission_gate'],
    docsUrl: 'https://www.esa.int/Applications/Observing_the_Earth/LSTM',
  },
  {
    sourceId: 'LANDSAT_NEXT_FUTURE',
    name: 'Landsat Next (future)',
    category: 'heat_land',
    status: 'future',
    providerType: 'future_mission',
    signals: ['ndvi', 'thermal_stress', 'ocean_color'],
    resolutionNote: 'Expected enhanced spectral/temporal design (pre-operational).',
    temporalNote: 'Launch and product readiness TBD.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['forest_carbon_deforestation_audit', 'water_pollution_evidence'],
    evidenceRole: 'Placeholder for next-gen Landsat continuity.',
    confidenceRole: 'Excluded until live.',
    limitations: ['Must not be invoked as live Landsat 8/9 replacement until operational.'],
    safetyRules: ['future_mission_gate'],
    docsUrl: 'https://www.usgs.gov/landsat-missions/landsat-next',
  },
  {
    sourceId: 'NASA_SBG_FUTURE',
    name: 'NASA SBG / surface biology and geology future architecture',
    category: 'heat_land',
    status: 'future',
    providerType: 'future_mission',
    signals: ['dust_mineral_proxy', 'methane_column'],
    resolutionNote: 'Program architecture spans multiple instruments and eras.',
    temporalNote: 'Future.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['biodiversity_habitat_integrity', 'methane_super_emitter_monitoring'],
    evidenceRole: 'Reserved for future spectroscopy + greenhouse gas layers.',
    confidenceRole: 'Excluded until live.',
    limitations: ['Programmatic; no single live public endpoint should be assumed yet.'],
    safetyRules: ['future_mission_gate'],
    docsUrl: 'https://sbg.jpl.nasa.gov/',
  },
  {
    sourceId: 'SMAP',
    name: 'NASA SMAP soil moisture',
    category: 'heat_land',
    status: 'live',
    providerType: 'satellite_mission',
    signals: ['soil_moisture'],
    resolutionNote: '36 km native; downscaled products vary.',
    temporalNote: '2–3 day revisit.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['drought_groundwater_risk', 'agriculture_carbon_water_efficiency', 'flood_risk_damage_intelligence'],
    evidenceRole: 'Root-zone moisture anomaly context for drought and irrigation screening.',
    confidenceRole: 'Moderate; stronger with in-situ probes and GRACE/FO hydro signals.',
    limitations: ['Coarse resolution mixes land covers.', 'Not a direct measure of groundwater pumping legality.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion'],
    docsUrl: 'https://smap.jpl.nasa.gov/',
  },
  {
    sourceId: 'GRACE_FO',
    name: 'GRACE / GRACE-FO terrestrial water storage',
    category: 'heat_land',
    status: 'live',
    providerType: 'satellite_mission',
    signals: ['gravity_water_storage'],
    resolutionNote: '~300 km equivalent smoothing scales for mass changes.',
    temporalNote: 'Monthly fields typical.',
    requiredInputs: ['lat', 'lng', 'dateRange', 'largeAoi'],
    businessUseCases: ['drought_groundwater_risk', 'dam_reservoir_river_integrity'],
    evidenceRole: 'Regional mass trend screening for aquifer stress and storage change context.',
    confidenceRole: 'Strong for large basins; weak for parcel-scale claims.',
    limitations: ['Cannot localize to a single well or small facility.', 'Signal mixes multiple hydrologic processes.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion'],
    docsUrl: 'https://www2.csr.utexas.edu/grace/',
  },
  {
    sourceId: 'DYNAMIC_WORLD',
    name: 'Dynamic World near-real-time land cover (Google/WRI)',
    category: 'heat_land',
    status: 'live',
    providerType: 'derived_product',
    signals: ['land_cover_change'],
    resolutionNote: '10 m classifications from Sentinel-2.',
    temporalNote: 'Near real-time updates with Sentinel cadence.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['illegal_mining_land_disturbance', 'forest_carbon_deforestation_audit', 'biodiversity_habitat_integrity'],
    evidenceRole: 'Probabilistic land cover transitions for disturbance triage.',
    confidenceRole: 'Medium; confirm with optical/SAR time series and field checks.',
    limitations: ['Classifier errors near spectrally similar classes.', 'Probabilities are not legal land-use determinations.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion'],
    docsUrl: 'https://dynamicworld.app/',
  },
  {
    sourceId: 'COMPANY_DISCLOSURE',
    name: 'Company disclosures (SEC / annual reports)',
    category: 'ground_truth_public_records',
    status: 'public_record',
    providerType: 'public_agency_dataset',
    signals: ['corporate_disclosure'],
    resolutionNote: 'Document-level; not geospatial by default.',
    temporalNote: 'Quarterly/annual cadence.',
    requiredInputs: ['companyName', 'facilityIdOptional'],
    businessUseCases: ['corporate_greenwashing_review', 'investor_climate_risk_intelligence', 'supplier_environmental_watch'],
    evidenceRole: 'Self-reported narrative and metrics for consistency checks against independent observations.',
    confidenceRole: 'High for “what the company claimed,” low for physical truth without corroboration.',
    limitations: ['Self-reporting bias; requires cross-source verification.', 'Not admissibility or legal advice.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion', 'no_registry_claim'],
    apiStatus: 'public_filings',
  },
  {
    sourceId: 'ESG_REPORT',
    name: 'ESG / sustainability reports',
    category: 'ground_truth_public_records',
    status: 'public_record',
    providerType: 'public_agency_dataset',
    signals: ['corporate_disclosure'],
    resolutionNote: 'Voluntary frameworks vary (GRI/ISSB/etc.).',
    temporalNote: 'Annual common.',
    requiredInputs: ['companyName'],
    businessUseCases: ['corporate_greenwashing_review', 'supplier_environmental_watch', 'investor_climate_risk_intelligence'],
    evidenceRole: 'Corporate narrative baseline for divergence analysis vs sensors and permits.',
    confidenceRole: 'Documentary only for claims found in report text.',
    limitations: ['Non-standard metrics; selective disclosure risk.', 'Does not prove on-site performance.'],
    safetyRules: ['no_auto_human_verify', 'no_viu_claim'],
  },
  {
    sourceId: 'REGULATORY_FILING',
    name: 'Regulatory filings (general)',
    category: 'ground_truth_public_records',
    status: 'public_record',
    providerType: 'public_agency_dataset',
    signals: ['regulatory_disclosure'],
    resolutionNote: 'Jurisdiction-specific portals and formats.',
    requiredInputs: ['facilityIdOptional', 'companyName', 'jurisdiction'],
    businessUseCases: ['environmental_litigation_support', 'government_transparency_dashboard', 'hazardous_waste_integrity_audit'],
    evidenceRole: 'Official record pointers for permits, violations, and dockets (where accessible).',
    confidenceRole: 'High for existence of a filed record; interpretation needs counsel workflow.',
    limitations: ['Access fragmentation; some records paywalled or delayed.', 'DPAL does not render legal conclusions.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion'],
    temporalNote: 'Docket and permit updates vary by agency.',
  },
  {
    sourceId: 'CARB_DATASET',
    name: 'CARB facility / emissions datasets (California)',
    category: 'ground_truth_public_records',
    status: 'public_record',
    providerType: 'public_agency_dataset',
    signals: ['facility_emissions_reported'],
    resolutionNote: 'Facility and sector tables; geocoding quality varies.',
    temporalNote: 'Annual reporting cycles; lagged releases.',
    requiredInputs: ['facilityIdOptional', 'lat', 'lng', 'reportingYear'],
    businessUseCases: ['industrial_air_pollution_watch', 'hazardous_waste_integrity_audit', 'government_transparency_dashboard'],
    evidenceRole: 'Reported emissions and facility attributes for California screening.',
    confidenceRole: 'High for reported fields; does not validate metered truth.',
    limitations: ['Reporting errors and revisions happen.', 'Not national coverage.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion'],
    apiStatus: 'dpal_carb_route_when_configured',
  },
  {
    sourceId: 'EPA_DATASET',
    name: 'EPA program datasets (ECHO/FRS/GHGRP/NEI as applicable)',
    category: 'ground_truth_public_records',
    status: 'public_record',
    providerType: 'public_agency_dataset',
    signals: ['facility_emissions_reported'],
    resolutionNote: 'Program-specific spatial resolution and refresh rates.',
    temporalNote: 'Varies by program (annual/quarterly).',
    requiredInputs: ['facilityIdOptional', 'lat', 'lng'],
    businessUseCases: [
      'water_pollution_evidence',
      'hazardous_waste_integrity_audit',
      'industrial_air_pollution_watch',
      'government_transparency_dashboard',
    ],
    evidenceRole: 'Permit, release, and facility registry context for triage.',
    confidenceRole: 'High for registry metadata; field conditions require inspection and sensors.',
    limitations: ['Incomplete geocodes; program exclusions apply.', 'Does not establish guilt or liability.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion'],
    apiStatus: 'envirofacts_and_epa_routes_when_configured',
  },
  {
    sourceId: 'FIELD_SENSOR',
    name: 'Field sensors (in-situ networks)',
    category: 'ground_truth_public_records',
    status: 'live',
    providerType: 'ground_observation',
    signals: ['field_measurement', 'weather_context'],
    resolutionNote: 'Point-scale; network density varies.',
    temporalNote: 'Minutes to hourly.',
    requiredInputs: ['sensorIdOrStation', 'lat', 'lng'],
    businessUseCases: ['water_pollution_evidence', 'drought_groundwater_risk', 'urban_heat_environmental_justice'],
    evidenceRole: 'Ground truth time series for validation and anomaly confirmation.',
    confidenceRole: 'High locally when calibrated; does not generalize across AOI without more stations.',
    limitations: ['Coverage gaps; maintenance and drift affect quality.', 'Access may require agency permissions.'],
    safetyRules: ['no_auto_human_verify', 'no_blockchain_claim'],
  },
  {
    sourceId: 'DRONE_SURVEY',
    name: 'Drone / UAS survey products',
    category: 'ground_truth_public_records',
    status: 'not_configured',
    providerType: 'ground_observation',
    signals: ['field_measurement'],
    resolutionNote: 'cm–m scale depending on altitude and sensor.',
    temporalNote: 'Campaign-based.',
    requiredInputs: ['aoiGeoJson', 'flightPlanMetadata', 'operatorAttestation'],
    businessUseCases: ['hazardous_waste_integrity_audit', 'illegal_mining_land_disturbance', 'real_estate_land_due_diligence'],
    evidenceRole: 'High-resolution orthomosaics and derived products for targeted validation.',
    confidenceRole: 'High when chain-of-custody and calibration metadata exist.',
    limitations: ['Requires licensed operators and airspace compliance.', 'Not automatic in DPAL until upload pipeline confirms metadata.'],
    safetyRules: ['no_auto_human_verify', 'field_validation_gate'],
  },
  {
    sourceId: 'LAB_SAMPLE',
    name: 'Laboratory analytical results',
    category: 'ground_truth_public_records',
    status: 'not_configured',
    providerType: 'ground_observation',
    signals: ['field_measurement'],
    resolutionNote: 'Sample-point truth for chemistry and biology.',
    temporalNote: 'Batch turnaround days to weeks.',
    requiredInputs: ['chainOfCustody', 'labMethodMetadata'],
    businessUseCases: ['water_pollution_evidence', 'hazardous_waste_integrity_audit', 'environmental_litigation_support'],
    evidenceRole: 'Defensible chemistry/biology measurements when metadata is complete.',
    confidenceRole: 'High for the sampled matrix and time window; not spatial extrapolation.',
    limitations: ['Point samples; spatial interpolation is uncertain.', 'DPAL ingestion requires verified upload workflow.'],
    safetyRules: ['no_auto_human_verify', 'field_validation_gate', 'no_legal_conclusion'],
  },
  {
    sourceId: 'COMMUNITY_REPORT',
    name: 'Community environmental reports',
    category: 'ground_truth_public_records',
    status: 'public_record',
    providerType: 'crowdsourced_or_operational',
    signals: ['field_measurement'],
    resolutionNote: 'Variable quality; often unstructured.',
    temporalNote: 'Event-driven.',
    requiredInputs: ['locationDescription', 'timestamp', 'mediaOptional'],
    businessUseCases: ['community_environmental_reporting', 'urban_heat_environmental_justice', 'flood_risk_damage_intelligence'],
    evidenceRole: 'Human observations for triage and routing to validators.',
    confidenceRole: 'Low to medium alone; increases with corroborating sensors and imagery.',
    limitations: ['Bias and duplication; verification required.', 'Not evidence of regulatory violation by itself.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion'],
  },
  {
    sourceId: 'QR_EVIDENCE',
    name: 'QR-linked evidence artifacts',
    category: 'ground_truth_public_records',
    status: 'live',
    providerType: 'ground_observation',
    signals: ['field_measurement'],
    resolutionNote: 'Links to digital artifacts with hash metadata when implemented.',
    temporalNote: 'Tied to capture time in metadata.',
    requiredInputs: ['qrPayload', 'hashOptional'],
    businessUseCases: ['community_environmental_reporting', 'supplier_environmental_watch', 'dpal_verified_impact_units'],
    evidenceRole: 'Traceable handoff between physical sampling and digital packet (metadata dependent).',
    confidenceRole: 'Medium-high if hash and custody metadata are present; low if not.',
    limitations: ['Does not imply blockchain anchoring unless explicitly recorded.', 'Spoofed QR risk without issuer controls.'],
    safetyRules: ['no_auto_human_verify', 'no_blockchain_claim', 'no_viu_claim'],
  },
  {
    sourceId: 'WEATHER_DATA',
    name: 'Weather and meteorological context (NOAA/NWS/etc.)',
    category: 'ground_truth_public_records',
    status: 'public_record',
    providerType: 'public_agency_dataset',
    signals: ['weather_context'],
    resolutionNote: 'Station and model blend products vary.',
    temporalNote: 'Hourly to daily.',
    requiredInputs: ['lat', 'lng', 'dateRange'],
    businessUseCases: ['flood_risk_damage_intelligence', 'wildfire_illegal_burn_monitoring', 'insurance_environmental_risk'],
    evidenceRole: 'Meteorological context for plume transport, fire weather, and flood windows.',
    confidenceRole: 'High for broad weather facts; plume attribution still needs chemistry/satellites.',
    limitations: ['Models are not observations; local microclimates differ.', 'Not emergency dispatch authority.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion'],
  },
  {
    sourceId: 'RIVER_TIDE_DATA',
    name: 'River gauges / tidal reference data',
    category: 'ground_truth_public_records',
    status: 'public_record',
    providerType: 'public_agency_dataset',
    signals: ['hydrology_gauge', 'weather_context'],
    resolutionNote: 'Point gauges along networks; datum and sensor errors matter.',
    temporalNote: 'Sub-daily common.',
    requiredInputs: ['stationIdOrLatLng', 'dateRange'],
    businessUseCases: ['dam_reservoir_river_integrity', 'flood_risk_damage_intelligence', 'water_pollution_evidence'],
    evidenceRole: 'Hydrologic stage/discharge context for flood and mixing screening.',
    confidenceRole: 'High at gauge; weaker far from gauge without hydraulic modeling.',
    limitations: ['Ice jams and backwater break simple interpretations.', 'Not a legal flood determination.'],
    safetyRules: ['no_auto_human_verify', 'no_legal_conclusion'],
  },
  {
    sourceId: 'INCIDENT_REPORT',
    name: 'Formal incident / situation reports',
    category: 'ground_truth_public_records',
    status: 'public_record',
    providerType: 'crowdsourced_or_operational',
    signals: ['field_measurement'],
    resolutionNote: 'Structured narratives and attachments.',
    temporalNote: 'Event timestamped.',
    requiredInputs: ['incidentIdOrRoom', 'timestamp'],
    businessUseCases: ['community_environmental_reporting', 'environmental_litigation_support', 'government_transparency_dashboard'],
    evidenceRole: 'Operational record for Situation Room workflows and audit trails (policy-controlled).',
    confidenceRole: 'Depends on authorship and corroboration; default pending verification.',
    limitations: ['Human-authored; may be incomplete at filing time.', 'Does not imply external verification.'],
    safetyRules: ['no_auto_human_verify', 'no_blockchain_claim'],
  },
  {
    sourceId: 'AIS_VESSEL_DATA',
    name: 'AIS vessel tracking (commercial or public feeds)',
    category: 'ground_truth_public_records',
    status: 'commercial',
    providerType: 'commercial_imagery',
    signals: ['vessel_tracking'],
    resolutionNote: 'Vessel-position broadcasts; gaps when AIS off or spoofed.',
    temporalNote: 'Near real-time with feed latency.',
    requiredInputs: ['aoiOrPort', 'dateRange', 'commercialKeyOptional'],
    businessUseCases: ['port_shipping_pollution', 'plastic_pollution_watch', 'supplier_environmental_watch'],
    evidenceRole: 'Maritime activity context for port and coastal screening.',
    confidenceRole: 'Medium; spoofing and coverage gaps limit certainty.',
    limitations: ['Legal use depends on feed license.', 'AIS off does not prove wrongdoing.'],
    safetyRules: ['commercial_gate', 'no_legal_conclusion'],
  },
  {
    sourceId: 'PLANET_SCOPE',
    name: 'PlanetScope (Planet Labs)',
    category: 'commercial_partner',
    status: 'commercial',
    providerType: 'commercial_imagery',
    signals: ['ndvi', 'land_cover_change'],
    resolutionNote: '3–5 m daily revisit where contracted.',
    temporalNote: 'Tasking and archive depend on contract.',
    requiredInputs: ['lat', 'lng', 'dateRange', 'commercialKey'],
    businessUseCases: ['illegal_mining_land_disturbance', 'forest_carbon_deforestation_audit', 'real_estate_land_due_diligence'],
    evidenceRole: 'High cadence optical change detection when purchased.',
    confidenceRole: 'Excluded from public-stack confidence unless executed.',
    limitations: ['Commercial license required.', 'Atmospheric correction still required for quantitative indices.'],
    safetyRules: ['commercial_gate', 'no_auto_human_verify'],
    docsUrl: 'https://www.planet.com/',
  },
  {
    sourceId: 'MAXAR_WORLDVIEW',
    name: 'Maxar WorldView optical',
    category: 'commercial_partner',
    status: 'commercial',
    providerType: 'commercial_imagery',
    signals: ['ndvi', 'land_cover_change'],
    resolutionNote: 'Sub-meter panchromatic / multispectral products.',
    temporalNote: 'Archive and tasking contract dependent.',
    requiredInputs: ['lat', 'lng', 'dateRange', 'commercialKey'],
    businessUseCases: ['real_estate_land_due_diligence', 'infrastructure_subsidence_monitoring', 'insurance_environmental_risk'],
    evidenceRole: 'High-resolution optical evidence for asset-scale review.',
    confidenceRole: 'High when delivered; not assumed available.',
    limitations: ['Cost and tasking constraints.', 'License terms govern redistribution.'],
    safetyRules: ['commercial_gate', 'no_auto_human_verify'],
    docsUrl: 'https://www.maxar.com/',
  },
  {
    sourceId: 'ICEYE_SAR',
    name: 'ICEYE SAR constellation',
    category: 'commercial_partner',
    status: 'commercial',
    providerType: 'commercial_imagery',
    signals: ['sar_flood', 'sar_deformation'],
    resolutionNote: 'Flood and change-detection products; resolution mode dependent.',
    temporalNote: 'Rapid revisit with large constellation.',
    requiredInputs: ['lat', 'lng', 'dateRange', 'commercialKey'],
    businessUseCases: ['flood_risk_damage_intelligence', 'insurance_environmental_risk', 'dam_reservoir_river_integrity'],
    evidenceRole: 'Commercial SAR flood and surface change evidence when purchased.',
    confidenceRole: 'Excluded unless contract execution confirms delivery.',
    limitations: ['Commercial license and analyst workflow required.', 'Interpretation needs hydrologic context.'],
    safetyRules: ['commercial_gate', 'no_legal_conclusion'],
    docsUrl: 'https://www.iceye.com/',
  },
  {
    sourceId: 'CAPELLA_SAR',
    name: 'Capella Space SAR',
    category: 'commercial_partner',
    status: 'commercial',
    providerType: 'commercial_imagery',
    signals: ['sar_deformation', 'sar_flood'],
    resolutionNote: 'Spotlight/strip modes; resolution tradeoffs.',
    temporalNote: 'Tasking-dependent.',
    requiredInputs: ['lat', 'lng', 'dateRange', 'commercialKey'],
    businessUseCases: ['infrastructure_subsidence_monitoring', 'illegal_mining_land_disturbance', 'insurance_environmental_risk'],
    evidenceRole: 'Commercial SAR for deformation and disturbance campaigns.',
    confidenceRole: 'Excluded unless purchased and processed.',
    limitations: ['Commercial contract required.', 'Geolocation and phase errors need QA.'],
    safetyRules: ['commercial_gate', 'no_auto_human_verify'],
    docsUrl: 'https://www.capellaspace.com/',
  },
] as const;

export type DpalSourceId = (typeof dpalSourceRegistry)[number]['sourceId'];

export const dpalSourceRegistryById: Readonly<Record<string, DpalSource>> = Object.fromEntries(
  dpalSourceRegistry.map((s) => [s.sourceId, s]),
);
